---
sidebar: sidebar 
permalink: nkfsosm_kfs_billing.html 
keywords: netapp, keystone, billing, Keystone billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing 
summary: La facturation Keystone 
---
= La facturation Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avec NetApp Keystone, vous bénéficiez d'une tarification en amont et prévisible pour votre abonnement au stockage.

Si vous préférez le modèle de consommation des dépenses opérationnelles (OpEx) aux dépenses d'investissement (CapEx) ou à la location, vous pouvez opter pour le modèle Keystone de paiement à l'utilisation pour vos besoins flexibles et évolutifs.

Keystone vous fournit les fonctionnalités de facturation suivantes :

* Vous pouvez payer en fonction des IOPS et de la capacité qui est dédiée à la latence pour répondre aux différents besoins des charges de travail. Les différents tiers de service de performance : Extreme, Premium, Standard et Value vous permettent de gérer votre stockage en fonction du niveau de service que vous avez acheté pour vos services Keystone.
* Il présente une facturation prévisible de la capacité engagée et du paiement à l'utilisation pour l'utilisation variable (en rafale).
* Vous pouvez sélectionner un prix de bundle pour le matériel, le système d'exploitation de base et le support pour un prix unitaire. Vous disposez d'une seule facture pour chaque type de stockage, service de fichier, bloc, objet ou service de stockage cloud.
* Choisissez une durée flexible pour les services et le paiement : vous pouvez opter pour 12 mois, 100 Tio ou plus par site. Vous pouvez ensuite procéder au renouvellement automatique pendant 12 mois ou vous rendre d'un mois à l'autre.


La facturation de Keystone repose sur la capacité engagement et sur la consommation en rafale variable.

Pour plus d'informations sur l'utilisation de la capacité engagée et en rafale, reportez-vous à la section link:nkfsosm_keystone_service_capacity_definitions.html["Définitions de capacité des services Keystone"].



== Facturation en fonction de la capacité engagement

Les capacités engagées désignent les capacités des différents services dans un seul abonnement, convenues par les parties concernées (NetApp/partenaire et client). Cette capacité est indiquée sur chaque commande Keystone et facturée indépendamment de la consommation réelle.

.Mesure de la capacité consommée
Dans le cadre du déploiement du service Keystone, NetApp contrôle en continu et mesure la consommation du service. Au moins une fois toutes les cinq minutes, un enregistrement de consommation est généré par le système, détaillant la capacité consommée actuelle de l'abonnement. Ces enregistrements sont agrégés au cours de la période de facturation afin de générer des factures et des rapports d'utilisation.



== Facturation en fonction de la consommation en rafale

Lorsque la capacité consommée est supérieure à la capacité requise pour un niveau de services donné, la consommation en rafale est enregistrée et des frais sont appliqués en conséquence. Ce processus se produit pour chaque enregistrement de consommation généré. La consommation en rafale reflète donc à la fois le montant et la durée de vos capacités surconsommées en plus de vos capacités engagées.



== Calendriers de facturation

Les services Keystone sont facturés mensuellement et annuellement.

.Facturation mensuelle
Les factures sont envoyées chaque mois. Pour le mois au cours duquel les services sont disponibles, une facture est envoyée le mois suivant. Par exemple, la facture des services que vous avez utilisés en janvier est livrée au début de février. Cette facture comprend les frais liés à la capacité engagée et, le cas échéant, à l'utilisation en rafale.

.Facturation annuelle
Une facture est générée au début de chaque année d'abonnement pour le paiement minimum de la capacité engagée. Il est généré à la date de début de l'abonnement. Une autre facture est envoyée à la fin d'un trimestre d'abonnement, qui comprend les frais applicables relatifs à toute utilisation en rafale accumulée au cours de ce trimestre. Si la capacité engagée est modifiée au cours d'un abonnement, une facture est envoyée le même jour que la modification de la capacité engagée, pour les paiements minimums au prorata pour le reste de l'année d'abonnement.

.Période de grâce pour la facturation en rafale
Au cours des 60 premiers jours de l'activation d'un abonnement, toute consommation supplémentaire que vous accumulez est enregistrée, mais non facturée sur votre facture de service Keystone. Ce délai de grâce vous permet de configurer votre stockage avec les paramètres AQoS (Adaptive Quality of Service) appropriés afin qu'il puisse être correctement contrôlé et facturé. Si vous configurez correctement votre système de stockage, vous pouvez éviter les frais de rafale inattendus. Toute utilisation en rafale accumulée après la période de grâce initiale de 60 jours sera facturée sur votre prochaine facture. Ce délai de grâce n'affecte aucune modification ou renouvellement de vos abonnements existants.



== Scénarios divers pour la facturation Keystone

Vous devez vous familiariser avec ces scénarios pour la facturation Keystone dans plusieurs scénarios.



=== Facturation des volumes clonés

Si les volumes sont clonés dans ONTAP et que vous les utilisez pour la sauvegarde et la restauration de vos données, vous pouvez continuer à utiliser ces clones sans paiements supplémentaires. Toutefois, les volumes clonés utilisés à d'autres fins dans votre entreprise pendant une durée étendue sont facturés.

Notez ce qui suit :

* Les volumes clones sont libres de se charger tant que leur taille est inférieure à 10 % du volume parent (capacité physique utilisée dans le volume clone par rapport à la capacité physique utilisée dans le volume parent).
* Il n'y a pas de période de grâce de 24 heures pour les volumes clonés, seule la taille du clone est prise en compte.
* Une fois que le volume clone dépasse 10 % de la taille physique du parent, le clone est facturé comme volume standard (capacité logique utilisée).




=== Facturation pour MetroCluster

La protection avancée des données utilise NetApp MetroCluster pour mettre en miroir les données entre deux clusters physiquement séparés. Sur les agrégats MetroCluster en miroir, les données sont écrites deux fois, une fois sur chaque cluster. Des frais de service Keystone pour la consommation de chaque côté de manière indépendante, pour obtenir deux enregistrements de consommation identiques. Si vous surveillez vos clusters via ONTAP System Manager (System Manager) ou Active IQ Unified Manager (Unified Manager), vous risquez de voir une différence entre la consommation signalée sur ces outils et les services Keystone. System Manager et Unified Manager ne signalent pas les volumes sur le cluster (distant) en miroir, et ce faisant, indiquent la moitié des metrics de consommation que le service Keystone fournit.

Par exemple : les sites A et B sont configurés dans une configuration MetroCluster. Lorsqu'un utilisateur crée un volume de 10 To sur le site A, un volume identique de 10 To est créé sur le site B. Keystone distingue à la fois les volumes et enregistre une consommation supplémentaire de 10 To dans chaque site, pour une augmentation totale de 20 To. System Manager et Unified Manager créent un volume de 10 To créé sur le site A.



=== Facturation des volumes temporaires

Il arrive que des volumes temporaires soient créés par ONTAP lors du déplacement de volumes. Ces volumes temporaires sont de courte durée, et la consommation sur ces volumes n'est pas mesurée pour la facturation.



=== Facturation et règles de QoS adaptatives

Keystone mesure la consommation en fonction des niveaux de service. Chaque niveau de service est associé à une règle de qualité de service (QoS) adaptative spécifique. Vous serez informé des détails de chaque politique de QoS pour vos services Keystone abonnés lors du déploiement. Lors des opérations de gestion du stockage, assurez-vous que vos volumes disposent des règles de QoS appropriées attribuées selon les niveaux de service que vous avez souscrits, afin d'éviter toute facturation inattendue.
Pour plus d'informations sur les règles de QoS dans ONTAP, reportez-vous à link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Débit garanti avec les QoS"^].



=== Facturation des destinations SnapMirror

Le prix du volume de destination SnapMirror est régi par la règle de QoS appliquée au niveau de service affecté à la source. Toutefois, si la source n'a pas de règle de QoS associée, la destination est facturée en fonction du niveau de service le plus bas disponible.



=== Facturation pour FlexGroups

Les FlexGroup sont facturées en fonction de la politique de QoS adaptative du FlexGroup. Les politiques de QoS de ses composants ne sont pas prises en compte.



=== Facturation des LUN

Pour les LUN, il s'agit généralement du même modèle de facturation que pour les volumes régis par les règles de QoS. Si des règles de QoS distinctes sont définies sur les LUN, alors :

* La taille de la LUN est comptabilisée pour consommation en fonction du niveau de service associé à cette LUN.
* Le reste de l'espace du volume, le cas échéant, est facturé conformément à la politique de QoS définie au niveau de service du volume.




=== Facturation de l'utilisation de FabricPool

Si les données sont hiérarchisées d'un système Keystone vers le stockage objet ONTAP simple Storage Service (S3) ou NetApp StorageGRID, la capacité consommée sur le Tier de stockage actif (système Keystone) est réduite par la quantité de données à hiérarchiser, ce qui a un impact sur la facturation. Indépendamment du fait que le stockage ONTAP S3 ou le système StorageGRID sont couverts par l'abonnement Keystone.

Pour Tiering de vos données dans un stockage objet tiers, contactez votre responsable de réussite Keystone.

Pour en savoir plus sur l'utilisation de la technologie FabricPool pour vos abonnements Keystone, reportez-vous à la section link:nkfsosm_tiering.html["Tiering"].



=== Facturation des volumes système et racine

Les volumes système et racine sont surveillés dans le cadre du contrôle global du service Keystone, mais ne sont pas comptabilisés ou facturés. La consommation sur ces volumes est exemptée de la facturation.
