---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Niveau de service des performances Keystone 
---
= Niveaux de services
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone offre une capacité de stockage des données avec des niveaux de service (niveaux de service) de performance prédéfinis ou des forfaits sur la base d'un abonnement. Chaque volume géré par les services Keystone est associé à un niveau de service.

Chaque niveau de services est défini par sa densité d'E/S, à savoir IOPS/Tio/volume. Il s'agit du rapport entre les performances (opérations d'entrée/sortie par seconde [IOPS]) et la capacité de stockage allouée (Tio), qui correspond au nombre d'IOPS/Tio à la latence moyenne par volume.

La densité d'E/S d'un volume est calculée à un intervalle horaire pour indiquer la densité d'E/S maximale. Les rapports de densité des E/S pour les volumes sont générés chaque mois.

Vous sélectionnez des niveaux de service en fonction de votre environnement de stockage, ainsi que des besoins de stockage et de consommation. Les niveaux de service de base sont disponibles par défaut. D'autres niveaux de service sont également disponibles si vous avez opté pour des services spécifiques. Par exemple, pour le service de protection des données, le niveau de service _Data-Protect <base-service-level>_ est attribué à votre abonnement.

Les niveaux de service de base pour les types de stockage fichier, bloc et objet sont répertoriés ici.



== Niveaux de service pour le stockage de fichiers

*Protocoles pris en charge* : NFS, CIFS, iSCSI et FC

|===


| *Niveau de service* | *Extrême* | *Premium* | *Standard* | *Valeur* 


| *Type de charge de travail* | Analytique, bases de données | VDI, applications de virtualisation, développement logiciel | Partages de fichiers, serveurs web | Sauvegarde 


| *Nombre maximal d'IOPS/Tio logique alloué par volume* | 12,288 | 4,096 | 512 | S/O 


| *IOPS cible/Tio logique allouées par volume* | 6,144 | 2,048 | 128 | S/O 


| *Nombre maximal de Mo/sec/Tio logique alloué par volume* | 384 | 128 | 16 | S/O 


| * Latence moyenne* | <1 ms | <2 ms | <17 ms | S/O 


| *Taille de bloc* 4+| 32 KO 
|===


=== En savoir plus sur les niveaux de service pour le stockage de fichiers

Les indicateurs de niveau de service de base dépendent des conditions suivantes :

* Les niveaux de service pour le stockage fichier et bloc prennent en charge ONTAP 9.7 et versions ultérieures.
* Les valeurs d'IOPS/Tio/volume, de Mo/sec/Tio/volume et de latence pour les niveaux de services sont basées sur la quantité de données logiques stockées dans le volume, la taille de bloc de 32 Ko et une combinaison aléatoire d'opérations d'E/S de 70 % en lecture et 30 % en écriture.
* La quantité réelle d'IOPS/Tio/volume et de Mo/sec/Tio/volume peut varier en fonction de la taille de bloc réelle ou estimée, de la simultanéité des workloads du système ou des opérations d'entrée/sortie.
* La latence n'inclut pas les éléments suivants :
+
** latence de l'hôte ou de l'application
** latence du réseau du client vers ou depuis les ports du contrôleur
** Frais généraux associés au transfert des données vers le magasin d'objets en cas de FabricPool
** La latence est automatiquement appliquée par la QoS pour maintenir les E/S dans les limites des limites maximales du niveau de service


* Les valeurs de latence ne s'appliquent pas aux opérations d'écriture MetroCluster. Ces opérations d'écriture dépendent de la distance entre les systèmes distants.
* Si une règle AQoS n'est pas attribuée à un ou plusieurs volumes d'un système de stockage, ces volumes sont considérés comme des volumes non conformes et aucun niveau de service cible n'est applicable à ces systèmes.
* La règle _IOPS attendues_ est destinée à FabricPool uniquement si la règle de Tiering est définie sur « aucun » et qu'aucun bloc n'est dans le cloud. _IOPS attendues_ est destiné aux volumes qui ne font pas partie d'une relation synchrone SnapMirror.
* Les opérations d'E/S des workloads doivent être équilibrées sur tous les contrôleurs déployés, comme le détermine l'ordre Keystone.




== Niveaux de service pour le stockage bloc

*Protocoles pris en charge* : FC et iSCSI

|===


| *Niveau de service* | *Extrême* | *Premium* | *Standard* 


| *Type de charge de travail* | HPC | Vidéosurveillance | Sauvegarde 


| *IOPS cibles/Tio* 3+| S/O 


| *IOPS max./Tio* | 5,500 | 4,000 | S/O 


| *Débit max. Mbit/s (32 Ko/IOP)* | 43 | 31 | S/O 


| * Latence moyenne* | <0.5 ms | <0.5 ms | S/O 


| *Taille de bloc* 3+| 32 KO 
|===


== Niveaux de service pour le stockage objet

*Protocole pris en charge* : S3

|===


| *Niveau de service* | Objet 


| *Type de charge de travail* | Référentiel multimédia, archivage 


| *IOPS cibles/Tio* | S/O 


| *IOPS max./Tio* | S/O 


| *Débit max. Mbit/s (32 Ko/IOP)* | S/O 


| * Latence moyenne* | S/O 
|===