---
sidebar: sidebar 
permalink: nkfsosm-keystone-and-aiq.html 
keywords: netapp, keystone, aiq keystone customers, Active IQ, Digital Advisor 
summary: Ce que les clients peuvent voir dans Active IQ pour la clé de voûte 
---
= Que peuvent voir les clients Flex Subscription dans Active IQ Digital Advisor ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous avez souscrit aux services NetApp Keystone Flex Subscription (Flex Subscription), vous pouvez afficher vos rapports d'utilisation et graphiques dans le tableau de bord Active IQ Digital Advisor (Digital Advisor).

Pour plus d'informations sur Digital Advisor, reportez-vous à la section link:https://docs.netapp.com/us-en/active-iq/index.html["Documentation de Digital Advisor"].

Si NetApp Service Engine est installé par défaut sur votre site, vous pouvez afficher les graphiques de consommation via l'interface NetApp Service Engine en plus de Digital Advisor. Toutefois, dans un environnement géré par le client, vous n'avez pas accès à l'interface NetApp Service Engine et vous pouvez afficher vos graphiques de capacité et vos rapports d'utilisation uniquement via le tableau de bord de Digital Advisor. Pour plus d'informations sur les environnements gérés par le client, reportez-vous à la section https://docs.netapp.com/us-en/keystone/nkfsosm_overview.html["Modèle opérationnel, rôles et responsabilités"]

L'intervalle de collecte des données de metrics de votre site est de 5 minutes.

En tant que client, si vous avez souscrit aux services Flex Subscription, vous pouvez afficher les informations suivantes sur Digital Advisor :

* *Widget Keystone Flex Subscription* : si vous vous êtes connecté à Digital Advisor, vous pouvez voir le widget *Keystone Flex Subscription* qui résume l'utilisation de la capacité par rapport à vos services Flex Subscription achetés.


Pour plus d'informations, voir link:https://docs.netapp.com/us-en/active-iq/view_keystone_capacity_utilization.html["Consultez l'utilisation de la capacité avec l'abonnement NetApp Keystone Flex"].

Pour plus d'informations sur l'onglet *abonnements Keystone*, reportez-vous à la section _Tableau de bord et reporting Digital Advisor pour Flex Subscription_.
