---
sidebar: sidebar 
permalink: nkfsfaq_netapp_service_engine_self-service_access_portal.html 
keywords: netapp, keystone, service, engine, self-service, acess, portal, 
summary: 'Portail d"accès en libre-service/moteur de service NetApp' 
---
= Portail d'accès en libre-service/moteur de service NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La FAQ suivante s'applique au moteur de service NetApp.

*Qu'est-ce que le moteur de service NetApp ?*

Le moteur de services NetApp est un portail en libre-service disponible sur le modèle géré par NetApp. Vous pouvez vous connecter et provisionner du stockage basé sur votre service NetApp Keystone Flex Subscription. Il fournit également des rapports sur les niveaux de consommation par rapport à leur abonnement et effectue toutes les demandes de service ou les modifications d'abonnement.

*Moteur de service NetApp requis dans le modèle exploité par le client?*

Sur le modèle opéré par le client, le moteur de service NetApp est requis. Il fournit des rapports de base sur les détails de consommation et est nécessaire de recueillir et de signaler les informations de facturation.

*Où est installé le moteur de service NetApp?*

Dans un modèle opéré par NetApp, le moteur de services NetApp est installé localement sur les ressources de calcul fournies par NetApp. Dans un modèle exploité par le client, NetApp Service Engine est installé sur les ressources de calcul fournies par le client.

*Qui peut se connecter au moteur de service NetApp?*

Les utilisateurs peuvent s'authentifier auprès de NetApp SSO ou des utilisateurs locaux configurés dans le moteur de service NetApp.

*Comment l'accès est-il contrôlé?*

NetApp Service Engine assure un contrôle d'accès basé sur des rôles (RBAC) et chaque utilisateur peut être associé à un rôle qui définit les actions qu'il peut effectuer. Le client utilise le moteur de service NetApp pour l'affectation du RBAC.

*Quels sont les contrôles d'accès disponibles?*

Les contrôles d'accès suivants sont disponibles :

* *Partner Admin.* un administrateur du côté partenaire qui a les droits de créer et de gérer des locataires, de gérer les abonnements pour les locataires, d'afficher les rapports d'utilisation et de gérer les aspects techniques du stockage.
* *Admin. Client/locataire* personne administrative du côté client qui a le droit de demander des modifications à l'abonnement, de créer de nouveaux utilisateurs et sous-locataires, ainsi que de créer et d'afficher des partages de fichiers, des disques et des compartiments.
* *Administrateur NetApp (lecture).* Un administrateur NetApp qui a accès à tous les composants du portail Web et qui peut afficher toutes les informations, notamment tous les abonnements NetApp Keystone Flex, aux partenaires et aux locataires, ainsi que le stockage. Toutefois, cet utilisateur ne dispose pas des autorisations nécessaires pour créer, modifier ou supprimer.
* *Admin NetApp* cet utilisateur dispose d'un accès complet et d'autorisations nécessaires pour effectuer toutes les fonctions du portail Web du moteur de services NetApp pour la gestion de l'abonnement NetApp Keystone Flex, ainsi que toutes les activités d'administration des partenaires et des locataires.


*Où puis-je voir la facturation par rapport à mon utilisation?*

Vous pouvez afficher les frais mensuels agrégés pour vos abonnements pour les trois derniers mois dans le widget *frais mensuels* du tableau de bord. Vous pouvez afficher des informations détaillées sur la facturation en cliquant sur le widget ou en accédant à *ADMINISTRATION* > *facturation*.
