---
sidebar: sidebar 
permalink: nkfsosm_netapp_global_services_and_support_center_@gssc@.html 
keywords: netapp, keystone, global, services, support, center, gssc, 
summary: 'Centre de support et de services NetApp (GSSC)' 
---
= Opérations des services Keystone
:allow-uri-read: 


[role="lead"]
Les services NetApp Keystone Keystone sont gérés à l'aide du Centre mondial de services et de support (GSSC), du responsable de la réussite NetApp Keystone et du responsable de la fourniture de services NetApp Keystone.



== Centre de support et de services NetApp (GSSC)

NetApp propose des services d'exploitation à distance aux clients NetApp Keystone. Ces services englobent plusieurs disciplines opérationnelles pour la gestion du stockage, notamment la gestion des ressources et de la configuration, la gestion de la capacité et des performances, la gestion du changement, les événements, la gestion des incidents et des problèmes, l'exécution des demandes de services et la création de rapports. NetApp fournira un état de contrôle et des preuves justificatives selon les besoins.



== Informations supplémentaires et coordonnées de l'assistance

L'équipe du Centre de support et de services NetApp (GSSC) soutient principalement les services fournis aux clients NetApp Keystone.

Émettre un ticket avec les détails appropriés du problème pour obtenir de l'aide.

Vous pouvez également utiliser les informations suivantes pour contacter l'équipe de support.

* Contacts Global Service :https://www.netapp.com/us/contact-us/support.aspx[]
* Pour un dossier ou un ticket ouvert devant être réaffecté de la manière suivante, envoyez un e-mail à l'une des adresses suivantes : Keystone.services@netapp.com Keystone.escalations@netapp.com
* NetApp utilise OpsRamp, une solution de passerelle distante basée dans le cloud pour surveiller de manière proactive l'environnement NetApp Keystone et vous connecter à des fins de dépannage. Pour plus d'informations sur OpsRamp, reportez-vous à la section https://www.opsramp.com/#[].



NOTE: Dans un modèle exploité par un partenaire, les demandes de service du locataire et du sous-locataire sont affectées au centre de service du partenaire. L'outil de support du partenaire pourrait être intégré aux applications OpsRamp et GSSC. Seuls les problèmes de niveau 3 sont transmis à NetApp via le GSSC.

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentation produit NetApphttps://docs.netapp.com["https://docs.netapp.com"^]

