---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: Présentation de NetApp Keystone 
---
= NetApp Keystone : questions les plus fréquemment posées (FAQ)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les questions suivantes donnent des réponses à vos questions fréquentes sur NetApp Keystone.

*Qu'est-ce que NetApp Keystone?*

NetApp Keystone est un portefeuille d'alternatives aux dépenses d'investissement (CapEx) sur site.
Pour plus d'informations, voir https://www.netapp.com/services/keystone/["NetApp Keystone"^].

*En quoi NetApp Keystone profite-t-il à mes clients?*

NetApp Keystone relie les piliers de notre stratégie CapEx et cloud hybride. Ce programme allie agilité, flexibilité financière et réduction des risques en matière de coûts pour aider les clients à répondre à leurs besoins de trésorerie et aux exigences métier.

La marque NetApp Keystone offre une gamme de solutions de paiement flexibles qui incluent le financement classique, le crédit-bail et les options fixes/variables pour les clients soucieux de leur trésorerie ainsi que les services Keystone.

*Services Keystone (OPEX, expérience de type cloud) :*
* Préférez 100% OpEx, donc les actifs ne se reverront pas sur le bilan de votre client
* Fournisseurs de services internes/externes cherchant à aligner les coûts avec l'utilisation/les revenus
* Charges de travail avec croissance imprévisible de la capacité
* Réaffectation des ressources INFORMATIQUES à partir de tâches de stockage classiques (migrations, mises à jour technologiques, mises à niveau, etc.)
* Solution à court terme avant la migration des workloads vers le cloud
* Rapatrier les workloads du cloud sur site

*Qu'est-ce que NetApp Keystone?*

NetApp Keystone est un nouveau modèle d'approvisionnement par abonnement sur site flexible. Il permet aux clients d'accélérer le retour sur investissement en éliminant les obstacles liés à la gestion des ressources et en passant par le long cycle d'approvisionnement. Les services Keystone permettent aux clients d'aligner le modèle économique sur leurs priorités commerciales. Pour plus d'informations, voir link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["ici"].

*Que signifie sur site?*

Ce site est défini comme un data Center détenu par le client ou un espace détenu par le client sur le site de colocation. Le client doit occuper l'espace, l'alimentation et le refroidissement.

*Quels sont les avantages des services Keystone?*

Avantages des services Keystone :

* Libérez vos équipes IT des tâches complexes liées au stockage et peuvent ainsi se concentrer sur la gestion des applications
* Réduit l'investissement initial
* Permet aux clients de répondre aux besoins sans surprovisionnement
* Alignement des coûts du stockage de données avec les besoins/activités de l'entreprise
* Simplifie le provisionnement de l'infrastructure en contournant les procédures d'approvisionnement complexes
* Sécurise les données sur site
* Permet un contrôle approprié de la conformité, des performances et de la sécurité pour plus d'informations, voir link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["ici"].

