---
sidebar: sidebar 
permalink: nkfsfaq_service_offer_details.html 
keywords: netapp, keystone, service, offer, details, 
summary: 'Détails de l"offre de service' 
---
= Offre de services Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les questions suivantes donnent des réponses à vos questions fréquentes sur l'offre de service NetApp Keystone Keystone.

*Quelle est la capacité minimale engagée?*

Pour un service d'abonnement NetApp Keystone, la capacité minimale allouée est de 100 Tio par site pour un ou plusieurs tiers de service.

*Quelle est la durée type d'un contrat de services Keystone?*

Le service Keystone propose des durées de 12, 24 et 36 mois.

*Comment puis-je accéder au stockage?*

Dans le modèle NetApp (standard), les contrôleurs de stockage (ONTAP System Manager ou l'accès administratif aux systèmes) sont détenus et gérés par NetApp. Vous pouvez contrôler votre stockage uniquement via l'interface utilisateur de Active IQ Digital Advisor.
Dans un déploiement géré par le client (ou Lite), où l'interface utilisateur de Active IQ Digital Advisor est principalement utilisée pour les fonctions de facturation, vous pouvez accéder aux contrôleurs de stockage, tels que Active IQ Unified Manager et ONTAP System Manager, et accéder directement aux clusters ONTAP.

*Comment puis-je gérer le service?*

Vous pouvez générer des tickets de support en fonction de vos besoins.

*Comment puis-je augmenter la capacité engagée dans un abonnement?*

Grâce à votre responsable NetApp Keystone Success Manager.

*L'augmentation de la capacité prolonge-t-elle le terme?*

Tous les ajouts sont à terme pour la période de validité existante, sauf si la demande est faite dans les 90 derniers jours de l'abonnement, auquel cas la durée doit être d'au moins 12 mois.

*Les abonnements peuvent-ils être co-définis entre eux?*

Non, les conditions d'abonnement sont indépendantes les unes des autres.

*Puis-je ajouter du stockage de sauvegarde à un abonnement existant?*

Dans le cas d'une sauvegarde, vous pouvez ajouter de la capacité à un abonnement existant pour un niveau de service existant ou nouveau, y compris les niveaux de service Standard ou Value. Cela ne modifie pas la durée de l'abonnement existant. Cependant, si vous souhaitez ajouter de la capacité au cours des 90 derniers jours de la période d'abonnement (c'est-à-dire les 90 derniers jours avant la fin de votre abonnement), vous devez également renouveler l'abonnement pendant au moins un an.

*Un nouvel abonnement a-t-il la flexibilité d'être accompagné d'une nouvelle période annuelle?*

Oui, les nouveaux abonnements peuvent avoir de nouvelles conditions distinctes de tous les abonnements existants.

*Les conditions d'abonnement du locataire peuvent-elles s'étendre au-delà de la durée d'abonnement du partenaire?*

Les abonnements aux locataires peuvent dépasser la période de validité des services Keystone en cours chez le partenaire. Un avertissement s'affiche lors de la création des abonnements ainsi que dans les rapports d'utilisation.

*Puis-je combiner plusieurs abonnements sur le même cluster ONTAP ?*

Non, chaque cluster est attribué à un abonnement particulier.

*Qui est le suivi et les opérations?*

Concernant le service opéré par NetApp, NetApp se charge de surveiller l'infrastructure à distance afin que le service se déroule selon les attentes convenues.

Le partenaire est responsable du service opéré par le partenaire : il se charge du contrôle à distance de l'infrastructure afin que le service se déroule selon les attentes convenues.

Pour le service opéré par le client, le client se charge du contrôle de l'infrastructure et de la résolution des problèmes à NetApp.

*Que se passe-t-il si je termine le service tôt?*

L'engagement de service minimum est de 12 mois. Si vous annulez le service tôt, la valeur résiduelle doit être payée à l'avance.

*Y a-t-il une occasion de convertir en achat après la fin de la période initiale?* non L'offre n'inclut pas une option permettant de convertir le produit en achat. En outre, les produits NetApp achetés précédemment ne font pas partie du cadre de ce programme.

*Puis-je demander une version de logiciel particulière?*

Non NetApp Keystone a standardisé la version logicielle sur l'ensemble de sa base client.

*Vais-je être informé des mises à niveau logicielles?*

Oui. Toutes les activités de maintenance et de mise à niveau sont communiquées au NetApp Keystone client et planifiées à une heure convenue mutuellement entre le client.
