---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Services NetApp Keystone
    url: "/index.html"
    entries:
    - title: Termes et description du service
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Définitions des capacités de service
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Niveaux de service dans Keystone
        url: "/nkfsosm_performance.html"
      - title: Metrics et définitions de niveaux de service
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Qualité de service adaptative dans Keystone
        url: "/aqos-kfs.html"
      - title: Facturation
        url: "/nkfsosm_kfs_billing.html"
      - title: Protection des données
        url: "/nkfsosm_data_protection.html"
      - title: Tiering
        url: "/nkfsosm_tiering.html"
      - title: Disque non retournable
        url: "/nkfsosm_nrd.html"
      - title: Aide des citoyens AUX ÉTATS-UNIS
        url: "/nkfsosm_uscs.html"
      - title: Keystone et Equinix
        url: "/nkfsosm_equinix.html"
    - title: Modèle opérationnel et responsabilités
      url: "/nkfsosm_overview.html"
    - title: Location et colocation
      url: "/nkfsosm_tenancy_overview.html"
    - title: Infrastructure Keystone
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Exigences du site
      url: "/nkfsosm_site_requirements.html"
    - title: Exploitation
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone et le conseiller digital Active IQ
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Affichez et générez des rapports à partir du conseiller digital Active
          IQ
        url: "/aiq-keystone-details.html"
  - title: Notes de version
    entries:
    - title: Quoi de neuf
      url: "/rn_whats_new.html"
    - title: Problèmes résolus
      url: "/rn_fixed_issues.html"
    - title: Problèmes connus
      url: "/rn_known_issues.html"
  - title: FAQ sur les abonnements Keystone
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Abonnements Keystone
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Détails de l'offre de service
      url: "/nkfsfaq_service_offer_details.html"
    - title: Modèle d'exploitation
      url: "/nkfsfaq_operating_models.html"
  - title: Mentions légales
    url: "/legal-notices.html"
