---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es
sidebar:
  entries:
  - title: Services NetApp Keystone
    url: "/index.html"
    entries:
    - title: Termes et description du service
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Définitions des capacités de service
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Niveaux de service dans Keystone
        url: "/nkfsosm_performance.html"
      - title: Metrics et définitions de niveaux de service
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Facturation
        url: "/nkfsosm_kfs_billing.html"
      - title: Protection des données
        url: "/nkfsosm_data_protection.html"
      - title: Tiering
        url: "/nkfsosm_tiering.html"
      - title: Disque non retournable
        url: "/nkfsosm_nrd.html"
      - title: Aide des citoyens AUX ÉTATS-UNIS
        url: "/nkfsosm_uscs.html"
      - title: Keystone et Equinix
        url: "/nkfsosm_equinix.html"
    - title: Modèle opérationnel et responsabilités
      url: "/nkfsosm_overview.html"
    - title: Location et colocation
      url: "/nkfsosm_tenancy_overview.html"
    - title: Infrastructure Keystone
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Exigences du site
      url: "/nkfsosm_site_requirements.html"
    - title: Exploitation
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone et le conseiller digital Active IQ
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Affichez et générez des rapports à partir du conseiller digital Active
          IQ
        url: "/aiq-keystone-details.html"
  - title: Notes de version
    entries:
    - title: Quoi de neuf
      url: "/rn_whats_new.html"
    - title: Problèmes résolus
      url: "/rn_fixed_issues.html"
    - title: Problèmes connus
      url: "/rn_known_issues.html"
  - title: FAQ sur les abonnements Keystone
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Abonnements Keystone
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Détails de l'offre de service
      url: "/nkfsfaq_service_offer_details.html"
    - title: Modèle d'exploitation
      url: "/nkfsfaq_operating_models.html"
    - title: Portail d'accès en libre-service/moteur de service NetApp
      url: "/nkfsfaq_netapp_service_engine_self-service_access_portal.html"
  - title: Interface Web du moteur de services NetApp
    url: "/sewebiug_overview.html"
    entries:
    - title: Comptes de facturation, abonnements, services et performances
      url: "/sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html"
    - title: Commencez
      entries:
      - title: Présentation
        url: "/sewebiug_getting_started_overview.html"
      - title: Connectez-vous
        url: "/sewebiug_log_in_to_the_netapp_service_engine_web_interface.html"
      - title: Rôles et opérations des fournisseurs de services et des clients
        url: "/sewebiug_partner_service_provider.html"
      - title: Sélectionnez le locataire
        url: "/sewebiug_select_tenant.html"
      - title: Afficher l'interface Web du moteur de services NetApp
        url: "/sewebiug_netapp_service_engine_web_interface_overview.html"
    - title: Afficher le tableau de bord des abonnements Keystone
      url: "/sewebiug_dashboard.html"
    - title: Afficher la facturation
      url: "/sewebiug_billing.html"
    - title: Utilisation des services de fichiers
      url: "/sewebiug_working_with_file_services_overview.html"
      entries:
      - title: Afficher les serveurs
        url: "/sewebiug_view_servers.html"
      - title: Créez un serveur de fichiers
        url: "/sewebiug_create_a_file_server.html"
      - title: Modifier le serveur de fichiers
        url: "/sewebiug_modify_file_server.html"
      - title: Supprimer le serveur de fichiers
        url: "/sewebiug_delete_file_server.html"
      - title: Afficher les partages
        url: "/sewebiug_view_shares.html"
      - title: Créez un partage de fichiers
        url: "/sewebiug_create_a_new_file_share.html"
      - title: Créer un partage de fichiers à partir d'un instantané
        url: "/sewebiug_create_file_share_from_snapshot.html"
      - title: Modifier un partage de fichiers
        url: "/sewebiug_modify_a_file_share.html"
      - title: Supprimer un partage de fichiers
        url: "/sewebiug_delete_a_file_share.html"
      - title: Créer un instantané ad hoc d'un partage de fichiers
        url: "/sewebiug_create_adhoc_snapshot_of_a_file_share.html"
    - title: Utilisation du stockage en mode bloc
      url: "/sewebiug_working_with_block_storage_overview.html"
      entries:
      - title: Travailler avec des groupes hôtes
        url: "/sewebiug_view_host_groups.html"
      - title: Afficher les disques
        url: "/sewebiug_view_disks.html"
      - title: Créer un disque
        url: "/sewebiug_create_a_new_disk.html"
      - title: Créer un disque à partir d'un snapshot
        url: "/sewebiug_create_a_disk_from_a_snapshot.html"
      - title: Modifier un disque
        url: "/sewebiug_modify_a_disk.html"
      - title: Supprimer un disque
        url: "/sewebiug_delete_a_disk.html"
      - title: Créer un snapshot ad hoc d'un disque
        url: "/sewebiug_create_an_adhoc_snapshot_of_a_disk.html"
    - title: Utilisation du stockage objet
      entries:
      - title: Présentation
        url: "/sewebiug_working_with_object_storage_overview.html"
      - title: Compartiments de vue
        url: "/sewebiug_view_buckets.html"
      - title: Initialiser le stockage d'objets
        url: "/sewebiug_initialize_object_storage.html"
      - title: Créer des compartiments
        url: "/sewebiug_create_buckets.html"
      - title: Afficher les utilisateurs et les groupes de stockage objet
        url: "/sewebiug_view_the_object_storage_group_and_users.html"
      - title: Créer un groupe de stockage objet
        url: "/sewebiug_create_an_object_storage_group.html"
      - title: Modifier un groupe de stockage d'objets
        url: "/sewebiug_modify_an_object_storage_group.html"
      - title: Supprime un groupe de stockage objet
        url: "/sewebiug_delete_an_object_storage_group.html"
      - title: Créer un utilisateur de stockage objet
        url: "/sewebiug_create_object_storage_user.html"
      - title: Modifier un utilisateur de stockage objet
        url: "/sewebiug_modify_an_object_storage_user.html"
      - title: Créez une clé S3 pour un utilisateur
        url: "/sewebiug_create_an_s3_key_for_a_user.html"
      - title: Supprimez une clé S3 d'un utilisateur
        url: "/sewebiug_delete_an_s3_key_for_a_user.html"
    - title: Gestion des services cloud
      entries:
      - title: Gestion des services cloud
        entries:
        - title: Présentation
          url: "/sewebiug_managing_subscribed_services_overview.html"
        - title: Afficher la liste des services auxquels vous êtes abonné
          url: "/sewebiug_view_a_list_of_subscribed_services.html"
        - title: Ajouter un service abonné
          url: "/sewebiug_add_a_subscribed_service.html"
        - title: Modifier les détails du service souscrit
          url: "/sewebiug_modify_the_subscribed_service_details.html"
        - title: Supprimer un service souscrit
          url: "/sewebiug_delete_a_subscribed_service.html"
      - title: Gérer Azure NetApp Files
        entries:
        - title: Gestion des comptes Azure NetApp
          url: "/sewebiug_managing_azure_netapp_accounts.html"
        - title: Gérez les pools de capacité Azure
          url: "/sewebiug_managing_azure_capacity_pools.html"
        - title: Gestion des volumes Azure
          url: "/sewebiug_managing_azure_volumes.html"
      - title: Gérez Cloud Volumes Service pour Google Cloud Platform
        url: "/sewebiug_managing_gcp_cvs.html"
    - title: Afficher les rapports
      url: "/sewebiug_working_with_reports.html"
    - title: Sauvegarder vos volumes
      url: "/sewebiug_back_up_file_shares_and_disks.html"
    - title: Gérer vos abonnements
      url: "/sewebiug_managing_subscriptions.html"
    - title: Gérer les demandes de service
      entries:
      - title: Présentation
        url: "/sewebiug_managing_service_requests_overview.html"
      - title: Demander un service
        url: "/sewebiug_raise_a_service_request.html"
      - title: Suivre une demande de service
        url: "/sewebiug_track_a_service_request.html"
      - title: Processus de demande de service
        url: "/sewebiug_service_request_process.html"
    - title: Effectuer des tâches administratives
      entries:
      - title: Gérer les utilisateurs
        entries:
        - title: Afficher la liste des utilisateurs
          url: "/sewebiug_view_a_list_of_users.html"
        - title: Ajouter un utilisateur
          url: "/sewebiug_add_a_user.html"
        - title: Modifier les détails de l'utilisateur
          url: "/sewebiug_modify_user_details.html"
        - title: Supprimer un utilisateur
          url: "/sewebiug_delete_a_user.html"
      - title: Gestion des locataires et sous-locataires
        url: "/sewebiug_managing_tenants_and_subtenants.html"
      - title: Afficher et gérer les alertes
        url: "/sewebiug_alerts.html"
    - title: Gérer les réseaux
      url: "/sewebiug_define_network_configurations.html"
  - title: Référence de l'API du moteur de service NetApp
    url: "/seapiref_overview_of_netapp_service_engine_apis.html"
    entries:
    - title: Autorisation et authentification
      url: "/seapiref_authorization_and_authentication.html"
    - title: API REST NetApp Service Engine
      url: "/seapiref_netapp_service_engine_rest_apis.html"
    - title: API grand public
      entries:
      - title: Présentation
        url: "/seapiref_consumer_apis_overview.html"
      - title: API d'orchestration cloud
        url: "/seapiref_cloud_orchestration_apis.html"
      - title: Les API de stockage bloc
        url: "/seapiref_block_storage_apis.html"
      - title: Les API de services de fichiers
        url: "/seapiref_file_services_apis.html"
      - title: API de stockage objet
        url: "/seapiref_object_storage_apis.html"
      - title: API de sauvegarde
        url: "/seapiref_backups_apis.html"
      - title: API de reporting
        url: "/seapiref_reporting_apis.html"
      - title: Créez des sous-réseaux à l'aide d'API
        url: "/seapiref_subnets_apis.html"
      - title: "(Grand public) les API d'administration"
        url: "/seapiref_@consumer@_administration_apis.html"
    - title: API d'administration
      entries:
      - title: Présentation
        url: "/seapiref_administrator_apis_overview.html"
      - title: Locataires
        url: "/seapiref_tenants.html"
      - title: Sous-locataires
        url: "/seapiref_subtenants.html"
      - title: Utilisateurs
        url: "/seapiref_users.html"
      - title: Zones
        url: "/seapiref_zones.html"
      - title: Régions
        url: "/seapiref_regions.html"
      - title: Clusters ONTAP
        url: "/seapiref_ontap_clusters.html"
      - title: Instances StorageGRID
        url: "/seapiref_storagegrid_instances.html"
      - title: Niveaux de services
        url: "/seapiref_service_levels.html"
      - title: Demandes de service
        url: "/seapiref_service_requests.html"
      - title: Emplois
        url: "/seapiref_jobs.html"
  - title: Mentions légales
    url: "/legal-notices.html"
