---
sidebar: sidebar 
permalink: seapiref_regions.html 
keywords: netapp, keystone, regions, 
summary: Régions Keystone 
---
= Régions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les méthodes répertoriées dans le tableau suivant pour créer, modifier et supprimer des régions. Pour plus d'informations sur les API qui vous permettent d'extraire des régions, reportez-vous à la section API d'administration (Consumer).

|===
| Méthode HTTP | Chemin | Description 


| `GET' | `/v2.1/régions` | Régions GET. 


| `GET' | `/v2.1/rerégions/{name}' | Obtenir les régions par nom. 


| «POST» | `/v2.1/régions` | Créer une nouvelle région. 


| `METTRE' | `/v2.1/rerégions/{name}' | Modifier les détails d'une région. 


| `SUPPRIMER' | `/v2.1/rerégions/{name}' | Supprimer une région. 
|===


== Attributs de région

Le tableau suivant répertorie les attributs de région.

|===
| Attribut | Type | Description 


| `id' | Chaîne | Identifiant unique de la région. 


| `nom' | Chaîne | Nom de la région. 


| `descriptions' | Chaîne | Description de la région. 
|===


== Extraire les régions

Utilisez la méthode indiquée dans le tableau suivant pour extraire toutes les régions ou un sous-ensemble de régions.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/régions` | Extraire les régions. | «offset» et «limite»– voir link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Pagination commune"] 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 4,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5e7bf44daab46c00014ce77f",
        "name": "au-east8",
        "description": "This is the new region description",
        "zones": []
      }
    ]
  }
}
....


== Récupérer une région par son nom

Utilisez la méthode indiquée dans le tableau suivant pour récupérer une région par nom.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/rerégions/{name}' | Récupérer une région par son nom. | `nom (chaîne)`: Le nom de la région. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "au-east1",
        "description": "string",
        "zones": [
          "au-east1-a"
        ]
      }
    ]
  }
}
....


== Créer une région

Utilisez la méthode indiquée dans le tableau suivant pour créer une région.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| «POST» | `/v2.1/régions` | Créer une nouvelle région. | Aucune 
|===
Attributs de corps de demande requis : `nom'

*Exemple corps de la demande :*

....
{
  "name": "MyRegionName",
  "description": "DescriptionOfMyRegion"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "Description": "DescriptionOfMyRegion",
        "user_id": "5bbee380a2df7a04d43acaee",
        "created": "0001-01-01T00:00:00Z",
        "tags": null
      }
    ]
  }
}
....


== Modifier une région

Utilisez la méthode indiquée dans le tableau suivant pour modifier une région.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `METTRE' | `/v2.1/rerégions/{name}' | Modifier une région identifiée par son nom. Vous pouvez modifier le nom et la description de la région. | `nom (chaîne)`: Le nom de la région. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
{
  "name": "MyRegionName",
  "description": "NewDescriptionOfMyRegion"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "description": "NewDescriptionOfMyRegion",
        "zones": []
      }
    ]
  }
}
....


== Supprimer une région

Utilisez la méthode indiquée dans le tableau suivant pour supprimer une région.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `SUPPRIMER' | `/v2.1/rerégions{name}` | Supprimer une région unique identifiée par son nom. Toutes les zones d'une région doivent être supprimées en premier. | `Nom (chaîne)`: Le nom de la région. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
No content for succesful delete
....