---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Demandes de service Keystone 
---
= Demandes de service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les méthodes répertoriées dans le tableau suivant pour créer et récupérer des demandes de service.

|===
| Méthode HTTP | Chemin | Description 


| `GET' | `/v2.1/tenants/{tenant_id}/servicequêtes` | Récupérer les demandes de service. 


| `GET' | `/v2.1/tenants/{tenant_id}/servicequêtes/{id}` | Récupérer une demande de service par ID. 


| «POST» | `/v2.1/tenants/{tenant_id}/servicequêtes/` | Créez une demande de service. 


| `GET' | `/v2.1/tenants/{tenant_id}/servicequêtes/categories» | Récupérer les catégories de demande de service. 
|===


=== Attributs des demandes de service

Le tableau suivant répertorie les attributs de demande de service.

|===
| Attribut | Type | Description 


| `ID' | Chaîne | Identifiant de la demande de service. Par exemple: `s RQ0035952014.` 


| « objet » | Chaîne | Objet de la demande de service. 


| «commentaire» | Chaîne | Un commentaire sur la demande de service 


| «catégorie» | Chaîne | La catégorie de la demande : sauvegarde, reprise après incident, technique, autre ou abonnement. 


| «priorité» | Chaîne | La priorité de la demande de service : très faible, faible, normale, élevée ou urgente. 


| `inscription` | Chaîne | Numéro d'abonnement Zuora. 


| «engagement» | –  a| 
Détails de l'engagement d'abonnement, notamment :

* Niveau de service (chaîne) : niveau de service : standard, Premium ou Extreme.
* New_engagement (entier) : nouvelle capacité totale requise.




| «zone» | Chaîne | Nom de la zone. 


| `subtenant_id' | Chaîne | Identifiant du sous-locataire. 


| `storage_object_type` | Chaîne | Type d'objet de stockage : serveur de fichiers ou magasin de blocs. 


| `storage_object_id` | Chaîne | Identificateur de l'objet de stockage. Par exemple: `5d2fb0fb4f47df00015274e3' 


| `ervice_type` | Chaîne | Le type de service : services de fichiers, stockage bloc ou stockage objet. 
|===


=== Récupérer les demandes de service

Utilisez la méthode indiquée dans le tableau suivant pour récupérer les catégories de demande de service pour le locataire spécifié.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/tenants/{tenant_id}/servicequêtes` | Récupérer les demandes de service. | `tenant_ID`: (Facultatif) Retourne les demandes de service pour le locataire spécifié. «offset» et «limite»– voir link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Pagination commune"] 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


=== Récupérer une demande de service par ID

Utilisez la méthode indiquée dans le tableau suivant pour récupérer une demande de service par ID de demande de service.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/tenants/{tenant_id}/servicequêtes/{id}` | Récupérer une demande de service par ID.  a| 
* `tenant_ID`: ID locataire
* `ID`: Demande de service IDPour exemple: SRQ0035952014


|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


=== Créez une demande de service

Utilisez la méthode indiquée dans le tableau suivant pour créer une demande de service.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| «POST» | `/v2.1/tenants/{tenant_id}/servicequêtes/categories» | Créez une demande de service. | `tenant_ID`: L'identifiant du locataire. 
|===
Attributs de corps de demande requis : les attributs requis dépendent de la catégorie de demande de service. Le tableau suivant répertorie les attributs du corps de la demande.

|===
| Catégorie | Obligatoire 


| Abonnement | la conscription et l'«engagement» 


| Reprise après incident | `storage_object_type`, `subtenant_id` et `storage_object_id` 


| Technique | `subtenant_ID` et `suservice_type` si `suervice_type` est des services de fichiers ou un stockage en bloc, la zone est requise. 


| Autre | Zone 
|===
*Exemple corps de la demande :*

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


=== Récupérer les catégories de demande de service

Le tableau suivant répertorie les catégories de demande de service de récupération pour un locataire spécifié.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/tenants/{tenant_id}/servicequêtes/categories» | Récupérer les catégories de demandes de service. | `tenant_ID:` (facultatif) Retourne les demandes de service pour un locataire spécifié. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....