---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Sous-locataires Keystone 
---
= Sous-locataires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les méthodes répertoriées dans le tableau suivant pour extraire, créer, modifier et supprimer des sous-locataires.

|===
| Méthode HTTP | Chemin | Description 


| `GET' | `/v2.1/sous-locataires» | Récupérer les sous-locataires. 


| `GET' | `/v2.1/sous-locataires/{id}' | Récupérez un sous-locataire par son ID. 


| «POST» | `/v2.1/subtenants` | Créez un nouveau sous-locataire. 


| `METTRE' | `/v2.1/sous-locataires/{id}' | Modifier les détails d'un sous-locataire. Vous pouvez modifier le nom du sous-locataire. 


| `SUPPRIMER' | `/v2.1/sous-locataires/{id}' | Supprimer un sous-locataire. 
|===


== Attributs du sous-locataire

Le tableau suivant répertorie les attributs du sous-locataire.

|===
| Attribut | Type | Description 


| `id' | Chaîne | Identifiant unique du sous-locataire. 


| `nom' | Chaîne | Nom du sous-locataire. 


| `code' | Chaîne | Code spécifié par le client (ou par défaut) qui représente le sous-locataire. 


| `tenant_id' | Chaîne | Identifiant du locataire auquel appartient le sous-locataire. 
|===


== Récupérer tous les sous-locataires

Utilisez la méthode indiquée dans le tableau suivant pour extraire tous les sous-locataires ou un sous-ensemble de tous les sous-locataires. Spécifier un `tenant_ID' ne renverra que les sous-locataires appartenant à ce locataire.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/sous-locataires» | Récupérer les sous-locataires. | `tenant_ID`: (Facultatif) Retourne les sous-locataires appartenant au locataire spécifié. décalage et limite– voir 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Récupérer un sous-locataire par ID

Utilisez la méthode indiquée ci-dessous pour récupérer un sous-locataire par ID.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/sous-locataires/{id}' | Récupérez le sous-locataire spécifié par l'ID. | `ID (chaîne)`: L'identifiant unique du sous-locataire. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Créez un sous-locataire

Utilisez la méthode indiquée dans le tableau suivant pour créer un sous-locataire.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| «POST» | `/v2.1/sous-locataires» | Créez un nouveau sous-locataire. | Aucune 
|===
Attributs de corps requis: `name', `code', `tenant_ID'

*Exemple corps de la demande :*

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Modifier un sous-locataire par ID

Utilisez la méthode indiquée dans le tableau suivant pour modifier un sous-locataire par ID.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `METTRE' | `/v2.1/sous-locataires/{id}' | Modifiez le sous-locataire spécifié par l'ID. Vous pouvez modifier le nom du sous-locataire. | `ID (chaîne)`: L'identifiant unique du sous-locataire. 
|===
Attributs de corps de demande requis : `nom'

*Exemple corps de la demande :*

....
{
  "name": "MyModifiedSubtenant"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Supprimer un sous-locataire par ID

Utilisez la méthode indiquée dans le tableau suivant pour supprimer un sous-locataire par ID.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `SUPPRIMER' | `/v2.1/sous-locataires/{id}' | Supprimez le sous-locataire spécifié par l'ID. | `ID (chaîne)`: L'identifiant unique du sous-locataire. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
No content for succesful delete
....