---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Niveaux de service Keystone 
---
= Niveaux de services
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les méthodes répertoriées dans le tableau suivant pour récupérer, créer, modifier et supprimer des niveaux de service.

|===
| Méthode HTTP | Chemin | Description 


| `GET' | `/v2.1/servicelevels` | Récupère tous les niveaux de service. 


| `GET' | `/v2.1/servicelevels/{id}' | Récupérer un niveau de service par ID. 


| «POST» | `/v2.1/servicelevels` | Créer un nouveau niveau de service. 


| `METTRE' | `/v2.1/servicelevels/{id}' | Modifiez les détails du niveau de service par ID. 


| `SUPPRIMER' | `/v2.1/servicelevels/{id}' | Supprimer un niveau de service. 
|===


=== Attributs de niveau de service

Le tableau suivant répertorie les attributs de niveau de service.

|===
| Attribut | Type | Description 


| `id' | Chaîne | Identifiant unique du niveau de service. 


| `nom' | Chaîne | Nom du niveau de service. 


| `descriptions' | Chaîne | La description du niveau de service. 


| `nom_politique' | Chaîne | Nom de la qualité de service (QoS) de niveau de service. Valeurs autorisées : nse_Value, nse_standard, nse_performance et nse_Extreme. 


| disponible | Booléen | Indique si le niveau de service est disponible. 


| "grandifathed" | Booléen | Indique si le niveau de service a été retiré. 


| `pic_iops_per_tb' | Entier | IOPS maximales possibles par Tio. 


| `nombre_d'iops_par_to attendu' | Entier | Nombre minimal d'IOPS attendues par Tio. 


| `absolute_min_iops' | Entier | Valeur d'IOPS minimale absolue utilisée comme valeur de remplacement lorsque le nombre d'IOPS attendu est inférieur à cette valeur. 


| `pic_iops_allocation' | Chaîne | Le pic d'allocation d'IOPS. Valeurs autorisées : espace_alloué et espace_utilisé. 


| `io_block_size_kb | Entier | Taille de bloc d'opération d'entrée/sortie (Kio). 


| `min_size_gb` | Entier | Taille minimale (Gio). 


| `max_size_gb` | Entier | Taille maximale (Gio). 


| `max_pic_iops` | Entier | IOPS maximales pour le niveau de service. 


| `max_attendue_iops` | Entier | La valeur maximale attendue d'IOPS. 


| `autogrow_max_percent' | Entier | Le pourcentage maximal de croissance automatique. 


| « ontap_aggregates » | –  a| 
La liste des agrégats ONTAP. Un agrégat ONTAP se compose des éléments suivants :

* `cluster_UIID: UUID de cluster ONTAP'
* `nom_agrégat: Nom_agrégat ONTAP`
* `aggr_UUID : UUID d'agrégat ONTAP'
* `node_name: ONTAP cluster node name` par exemple :


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| `primary_volume_defaults' | –  a| 
* Snapshot_auto_delete_target_free_space (entier) : cette option spécifie le pourcentage d'espace libre auquel la suppression automatique des copies Snapshot doit s'arrêter.
* auto_size_mode (chaîne de caractères) : mode autosize du volume. Valeurs autorisées : Désactivé, croissance, développement_réduction par exemple :


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


=== Récupérer les niveaux de service

Utilisez la méthode indiquée dans le tableau suivant pour récupérer tous les niveaux de service.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/servicelevels` | Récupère tous les niveaux de service. | Aucune 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== Récupère les niveaux de service par nom

Utilisez la méthode indiquée dans le tableau suivant pour récupérer les niveaux de service par nom.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/servicelevels/{name}' | Récupérer un niveau de service par nom. | `name (chaîne)`: Le nom du niveau de service. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== Créer un niveau de service

Utilisez la méthode indiquée dans le tableau suivant pour créer un niveau de service.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| «POST» | `/v2.1/servicelevels` | Créer un niveau de service. | Aucune 
|===
Attributs de corps de demande requis: `name', `policy_name'

*Exemple corps de la demande :*

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


=== Modifier un niveau de service

Utilisez la méthode indiquée dans le tableau suivant pour modifier un niveau de service.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `METTRE' | `/v2.1/servicelevels/{name}' | Modifier les détails d'un niveau de service. | `name (chaîne)`: Le nom du niveau de service. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Exemple de corps de réponse :*

....
TBA
....


=== Supprimer le niveau de service par ID

Utilisez la méthode indiquée dans le tableau suivant pour supprimer un niveau de service par ID.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `SUPPRIMER' | `/v2.1/servicelevels/{name}' | Supprimez le niveau de service identifié par l'ID. | `name (chaîne)`: Le nom du niveau de service. 
|===
*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
No content for succesful delete
....