---
sidebar: sidebar 
permalink: seapiref_backups_apis.html 
keywords: netapp, keystone, backups, apis, 
summary: API de sauvegarde Keystone 
---
= API de sauvegarde
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser l'API de sauvegarde pour afficher et gérer les sauvegardes ou points de restauration des volumes (partages de fichiers et disques) de votre environnement.

[cols="1,1,3,2"]
|===
| Verb. HTTP | Chemin | Description | Paramètres obligatoires/corps de la demande 


 a| 
`GET'
 a| 
`/v2.1/backups`
| Vous pouvez récupérer les détails de tous les objets de sauvegarde pour tous les volumes créés pour le sous-locataire. Récupère les détails du volume source et de l'objet de sauvegarde, tels que la stratégie de sauvegarde, la zone et les balises.  a| 
`offset': Nombre d'éléments à ignorer avant de commencer à collecter le jeu de résultats. «Limite»: Le nombre d'articles à retourner.



 a| 
`GET'
 a| 
`/v2.1/backups/{id}'
| Vous pouvez récupérer les détails d'un objet de sauvegarde spécifique créé pour un volume pour le sous-locataire. Récupère les détails du volume source et de l'objet de sauvegarde, tels que la stratégie de sauvegarde, la zone et les balises, en fonction de l'ID saisi.  a| 
`ID`: L'ID de l'objet de sauvegarde.



 a| 
`GET'
 a| 
`/v2.1/backups/{id}/``référence_points''
| Vous pouvez récupérer les détails de tous les points de restauration d'un objet de sauvegarde spécifique. Les détails, tels que l'horodatage et le nom, sont récupérés.  a| 
`ID`: L'ID de l'objet de sauvegarde.



 a| 
`GET'
 a| 
`/v2.1/backups/{id}/``référence_points/{nom}'
| Vous pouvez récupérer les détails de n'importe quel point de restauration d'un objet de sauvegarde spécifique. Les détails, tels que l'horodatage et le nom, sont récupérés.  a| 
`ID`: L'ID de l'objet de sauvegarde. «Nom»: Le nom du point de récupération.



 a| 
«POST»
 a| 
`/v2.1/backups`
| Vous pouvez créer un objet de sauvegarde pour un volume source spécifique. Ajoutez les valeurs dans le corps de la demande pour créer un objet de sauvegarde avec les paramètres spécifiés, tels que la stratégie de sauvegarde, le nombre de copies de sauvegarde à conserver et l'ID de ressource source.  a| 
`` { « primary_Resource_type »: «<Resource Type> », « source_Resource_ID »: «<ID> », « backup_zone »: «<Backup zone> », « Backup_policy »: { « Daily_backups_to_keep »: <nombre de sauvegardes quotidiennes à conserver>, « weekly_backs », « numéro_à conserver », « N_sauvegardes_à conserver », « nombre de sauvegardes_sauvegardes_à conserver », « nombre_à conserver », « nombre_sauvegardes_à garder : », « nombre_sauvegardes_à garder : », « nombre_à conserver : », « nombre_sauvegardes_1> "<Tag N>" } ``



 a| 
«POST»
 a| 
`/v2.1/backups/{id}/tags`
| Vous pouvez créer ou remplacer des balises pour un objet de sauvegarde pour votre sous-locataire. Ajoutez l'ID de l'objet de sauvegarde et les valeurs des balises au format « paire clé:valeur » dans le corps de la demande.  a| 
`ID`: L'ID de l'objet de sauvegarde. `` { "key1": "<Tag 1>", "key2": "<Tag 2>", "keyN": "<Tag N>" } ``



 a| 
`PATCHS'
 a| 
`/v2.1/backups/{id}'
 a| 
Vous pouvez modifier tout objet de sauvegarde d'un volume en fonction de son ID. Ajoutez l'ID de l'objet de sauvegarde et les valeurs que vous souhaitez modifier dans le corps de la demande, telles que les détails de la stratégie de sauvegarde, le nombre de sauvegardes à conserver et l'ID de ressource source.

[NOTE]
====
Vous pouvez rendre un objet de sauvegarde orphelin en définissant la valeur du paramètre `source_Resource_ID' comme valeur nulle dans votre requête `PATCH`. Cela supprime la relation SnapMirror, mais conserve le volume de sauvegarde et les points de récupération sous celle-ci.

==== a| 
`ID`: L'ID de l'objet de sauvegarde. `` { « source_Resource_ID »: « < ID ressource> », « backup_policy »: { « Daily_backups_to_keep »: <nombre de sauvegardes quotidiennes à conserver>, « weekly_backups_to_keep »: <nombre de sauvegardes hebdomadaires à conserver }}, « key1} à conserver », « Tag 1 », « Tag à conserver », « N_sauvegardes_1 3 »



 a| 
`SUPPRIMER'
 a| 
`/v2.1/backups/{id}'
| Vous pouvez supprimer n'importe quel objet de sauvegarde, ainsi que tous les points de restauration, pour un volume.  a| 
`ID`: L'ID de l'objet de sauvegarde.



 a| 
`SUPPRIMER'
 a| 
`/v2.1/backups/{id}/``référence_points/{nom}'
| Vous pouvez supprimer tout point de récupération d'un objet de sauvegarde spécifique d'un volume.  a| 
`ID`: L'ID de l'objet de sauvegarde. «Nom»: Le nom du point de récupération.

|===