---
sidebar: sidebar 
permalink: seapiref_subnets_apis.html 
keywords: netapp, keystone, subnets, networks, apis 
summary: API réseau Keystone 
---
= Définissez des configurations réseau avec des API de sous-réseau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser des API de sous-réseaux pour afficher et créer des sous-réseaux pour votre sous-locataire et votre zone. Vous pouvez les utiliser pour définir votre configuration réseau.

[cols="1,1,3,2"]
|===
| Verb. HTTP | Chemin | Description | Paramètres obligatoires/corps de la demande 


 a| 
`GET'
 a| 
`/v2.1/tenants/{tenant_id}/` `zones/{zone_name}/sous-réseaux`
| Vous pouvez récupérer tous les objets de sous-réseau d'un locataire et d'une zone. Récupère les détails du sous-réseau, tels que VLAN, sous-tenant, zone, routes, et balises.  a| 
`tenant_ID': L'ID du locataire. `nom_zone': Le nom de la zone. `offset': Nombre d'éléments à ignorer avant de commencer à collecter le jeu de résultats. «Limite»: Le nombre d'articles à retourner.



 a| 
`GET'
 a| 
`/v2.1/tenants/{tenant_id}/` `zones/{zone_name}/sous-réseaux/' `{id}'
| Vous pouvez récupérer les détails d'un objet de sous-réseau spécifique créé pour un tenant et une zone. Récupère les détails du sous-réseau, tels que VLAN, sous-tenant, zone, routes, Et les étiquettes basées sur l'ID saisi.  a| 
`tenant_ID': L'ID du locataire. `nom_zone': Le nom de la zone. `ID`: L'ID du sous-réseau.



 a| 
«POST»
 a| 
`/v2.1/tenants/{tenant_id}/` `zones/{zone_name}/sous-réseaux`
| Vous pouvez créer un objet de sous-réseau pour un locataire et une zone spécifiques. Ajoutez les valeurs dans le corps de la requête pour créer un objet de sous-tenant avec les paramètres spécifiés, tels que nom, VLAN, CIDR, ID de sous-tenant, routes, et balises.  a| 
`tenant_ID': L'ID du locataire. `nom_zone': Le nom de la zone. `` { "nom": "Chaîne", "vlan": "1000", "cidr": "10.0.0.0/24", "subtenant_ID": "5d2fb0fb4f47df00015274e3", "routes": ["destination }": "10.0 10.0.0.0 0.1/24 20", "valeur": "Key1", "valeur": "Valeur", "valeur": "Valeur": "1", "valeur" "valeur" "valeur": "1"" "valeur" "valeur", "valeur" "1"""



 a| 
«POST»
 a| 
`/v2.1/tenants/{tenant_id}/` `zones/{zone_name}/sous-réseaux/' `{id}/tags`
| Vous pouvez créer ou remplacer des balises pour un objet de sous-réseau de votre locataire. Ajoutez l'ID de l'objet sous-réseau et les valeurs des balises au format « paire clé:valeur » dans le corps de la demande.  a| 
`tenant_ID': L'ID du locataire. `nom_zone': Le nom de la zone. `ID`: L'ID de l'objet de sauvegarde. `` { "key1": "<Tag 1>", "key2": "<Tag 2>", "keyN": "<Tag N>" } ``

|===