---
sidebar: sidebar 
permalink: seapiref_authorization_and_authentication.html 
keywords: netapp, keystone, authorization, authentication, 
summary: Autorisation et authentification Keystone 
---
= Autorisation et authentification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'API REST NetApp Service Engine est accessible depuis n'importe quel navigateur web ou plateforme de programmation pouvant émettre des requêtes HTTP. NetApp Service Engine prend en charge un mécanisme d'authentification HTTP de base ainsi que l'authentification Java Web Token (JWT) Bearder. Avant d'appeler une API, vous devez authentifier un utilisateur.

Pour les API de référence, vous pouvez vous connecter à l'interface Web NetApp Service Engine et afficher l'interface swagger à partir du *volet de navigation gauche > support > Documentation API*.



== Codes d'état HTTP

Lors de l'exécution des API ou de la résolution de problèmes, vous devez connaître les divers codes d'état HTTP et codes d'erreur utilisés par les API des moteurs de services NetApp.

Le tableau suivant répertorie les codes d'erreur liés à l'authentification.

|===
| Code d'état HTTP | Titre du code de statut | Description 


| 200 | OK | Renvoyé lors de l'exécution réussie des appels d'API synchrone. 


| 201 | Créé | Création de nouvelles ressources par des appels synchrones, tels que la configuration d'Active Directory. 


| 202 | Accepté | Renvoyé lors de l'exécution réussie d'appels asynchrones pour les fonctions de provisionnement, telles que la création de LUN et de partages de fichiers. 


| 400 | Demande non valide | Indique un échec de validation de l'entrée. L'utilisateur doit corriger les entrées, par exemple les clés valides dans un corps de demande. 


| 401 | Demande non autorisée | Vous n'êtes pas autorisé à afficher la ressource/non autorisé. 


| 403 | Demande interdite | Il est interdit d'accéder à la ressource que vous tentez d'atteindre. 


| 404 | Ressource introuvable | La ressource que vous avez essayé de joindre est introuvable. 


| 405 | Méthode non autorisée | Méthode non autorisée. 


| 412 | Echec de la condition préalable | Une ou plusieurs conditions préalables n'ont pas été remplies. 


| 500 | Erreur interne du serveur | Erreur interne du serveur. Impossible d'obtenir une réponse du serveur. Cette erreur interne du serveur peut ou non être permanente. Par exemple, si vous exécutez une opération GET ou GET ET recevez cette erreur, il est recommandé de répéter cette opération pour un minimum de cinq tentatives. S'il s'agit d'une erreur permanente, le code d'état renvoyé continue à être 500. Si l'opération réussit, le code d'état renvoyé est 200. 
|===


== Recommandations pour l'utilisation des API

Lors de l'utilisation d'API, vous devez respecter certaines pratiques recommandées :

* Pour une exécution valide, assurez-vous que tous les types de contenu de réponse sont au format suivant :
+
....
application/json
....
* Lors de la mise à jour des valeurs de tableau, vous devez mettre à jour toute la chaîne de valeurs. Vous ne pouvez pas ajouter de valeurs à un tableau : vous ne pouvez remplacer qu'un tableau existant.
* Évitez d'interroger les objets en utilisant une combinaison des opérateurs de filtre joker (`*`) et pipe (`|`). Il est possible que le nombre d'objets soit incorrect.

