---
sidebar: sidebar 
permalink: seapiref_reporting_apis.html 
keywords: netapp, keystone, reporting, apis, 
summary: API de reporting Keystone 
---
= API de reporting
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les méthodes du tableau suivant pour extraire et générer des rapports.

|===
| Méthode HTTP | Chemin | Description 


| `GET' | `/v2.1/reports` | Extraire la liste de tous les rapports. 


| «POST» | `/v2.1/reports/{filename}' | Récupérer un rapport. 
|===


== Récupérer une liste de rapports

Utilisez la méthode indiquée dans le tableau suivant pour récupérer une liste de rapports.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/reports` | Récupérer tous les rapports disponibles pour un locataire. Les rapports peuvent être filtrés par plage de dates.  a| 
* `tenant_id (chaîne)'
* `sstart(string)`: Récupérez des rapports plus récents que la date spécifiée au début.
* `end (chaîne)': Récupère les rapports antérieurs à la date spécifiée à la fin


|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....


=== Récupérer un rapport identifié par nom de fichier

Utilisez la méthode du tableau suivant pour récupérer un rapport identifié par le nom du fichier.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/reports/{filename}' | Récupérer un rapport identifié par le nom de fichier. | `filename (chaîne)`: Le nom du fichier de rapport. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....