---
sidebar: sidebar 
permalink: seapiref_file_services_apis.html 
keywords: netapp, keystone, file services, file servers, file shares, apis 
summary: Les API de services de fichiers Keystone 
---
= Les API de services de fichiers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les API Services de fichiers pour afficher et gérer vos serveurs de fichiers et vos partages de fichiers.

Avant de créer des partages de fichiers, vous devez créer des serveurs de fichiers pour les héberger.



== API de serveurs de fichiers

Vous pouvez utiliser les API serveurs de fichiers pour afficher et gérer vos serveurs de fichiers. Pour plus d'informations sur les serveurs de fichiers, reportez-vous à la section link:hsewebiug_create_a_file_server.html["Créez un serveur de fichiers"].

[cols="1,1,3,2"]
|===
| Verb. HTTP | Chemin | Description | Paramètres obligatoires/corps de la demande 


 a| 
`GET'
 a| 
`/v2.1/serveurs de fichiers`
| Vous pouvez récupérer les détails de tous vos serveurs de fichiers. Récupère les détails des serveurs de fichiers, tels que l'ID du serveur de fichiers, le nom, la région, la zone, le locataire, et balises.  a| 
`offset': Nombre d'éléments à ignorer avant de commencer à collecter le jeu de résultats. «Limite»: Le nombre d'articles à retourner.



 a| 
`GET'
 a| 
`/v2.1/serveurs de fichiers/{id}'
| Vous pouvez récupérer les détails d'un serveur de fichiers spécifique. Récupère les détails du serveur de fichiers, tels que le nom, la région, la zone, le locataire, Et les étiquettes basées sur l'ID saisi.  a| 
`ID`: L'ID du serveur de fichiers.



 a| 
«POST»
 a| 
`/v2.1/serveurs de fichiers`
| Vous pouvez créer un serveur de fichiers. Ajoutez les valeurs dans le corps de la demande pour créer un serveur de fichiers avec les paramètres spécifiés, tels que nom, ID de sous-locataire, zone, ID de sous-réseau.  a| 
`name`: Le nom du serveur de fichiers. `subtenant_ID`: L'ID du sous-locataire. «Zone»: Le nom de la zone. `subnet_ID`: L'ID du sous-réseau.



 a| 
«POST»
 a| 
`/v2.1/serveurs de fichiers/{id}/` `tags`
| Vous pouvez créer ou remplacer des balises pour un serveur de fichiers. Ajoutez l'ID du serveur de fichiers et les valeurs des balises dans le format "paire clé:valeur" dans le corps de la demande.  a| 
`ID`: L'ID du serveur de fichiers.



 a| 
`METTRE'
 a| 
`/v2.1/serveurs de fichiers/{id}'
| Vous pouvez modifier n'importe quel serveur de fichiers en fonction de son ID. Ajoutez l'ID du serveur de fichiers et les valeurs que vous souhaitez modifier dans le corps de la demande, telles que le nom, le protocole, la zone, la région et les balises.  a| 
`ID`: L'ID du serveur de fichiers.



 a| 
`SUPPRIMER'
 a| 
`/v2.1/serveurs de fichiers/{id}'
 a| 
Vous pouvez supprimer n'importe quel serveur de fichiers par son ID.
 a| 
`ID`: L'ID du serveur de fichiers.

|===
[NOTE]
====
Avant de supprimer un serveur de fichiers, vous devez supprimer tous les partages de fichiers qui lui sont mappés.

Après la suppression des serveurs de fichiers compatibles CIFS, l'objet ordinateur Active Directory reste actif. Demandez à votre administrateur Active Directory de supprimer manuellement l'objet ordinateur du serveur de fichiers supprimé d'Active Directory.

====


== API de partages de fichiers

Vous pouvez utiliser les API de partages de fichiers pour afficher et gérer vos partages de fichiers. Pour plus d'informations sur les partages de fichiers, reportez-vous à la section link:sewebiug_create_a_new_file_share.html["Créez un partage de fichiers"].

[cols="1,1,3,2"]
|===
| Verb. HTTP | Chemin | Description | Paramètres obligatoires/corps de la demande 


 a| 
`GET'
 a| 
`/v2.1/fileshres`
| Vous pouvez récupérer les détails de tous vos partages de fichiers. Récupère les détails des partages de fichiers, tels que l'ID, le nom, la règle de snapshot, les protocoles, Adresse IP du serveur de fichiers et balises.  a| 
`offset': Nombre d'éléments à ignorer avant de commencer à collecter le jeu de résultats. «Limite»: Le nombre d'articles à retourner.



 a| 
`GET'
 a| 
`/v2.1/fileshres/{id}'
| Vous pouvez récupérer les détails d'un partage de fichiers spécifique. Récupère les détails du partage de fichiers, tels que l'ID, le nom, la règle de snapshot, les protocoles, l'adresse IP du serveur de fichiers, Et les étiquettes basées sur l'ID saisi.  a| 
`ID`: L'ID du partage de fichiers.



 a| 
«POST»
 a| 
`/v2.1/fileshres`
| Vous pouvez créer un partage de fichiers. Ajoutez les valeurs dans le corps de la demande pour créer un partage de fichiers avec les paramètres spécifiés, tels que ID, nom, stratégie d'instantané, protocoles, Adresse IP du serveur de fichiers et balises.  a| 
`name`: Le nom du partage de fichiers. `slièvre_path`: Le chemin du partage de fichiers. `filerver_ID` : ID du serveur de fichiers. `mettre_gb`: La taille du partage de fichiers en GBs. `niveau_service`: Le nom du niveau de service s'applique: Standard, Premium, Premium-Tiering, Extreme ou Extreme-Tiering. `protocole`: Protocole utilisé pour accéder au partage de fichiers (NFS, CIFS ou multi-protocole). `Security_style`: Le style de sécurité (Unix ou NTFS). `export_policy': La politique d'exportation du partage de fichiers.



 a| 
«POST»
 a| 
`/v2.1/fileshres/{id}/``napshot/{name}'
| Vous pouvez créer un instantané d'un partage de fichiers.  a| 
`ID`: L'ID du partage de fichiers. `name`: Le nom du snapshot.



 a| 
«POST»
 a| 
`/v2.1/fileshres/{id}/` `tags`
| Vous pouvez créer ou remplacer des balises pour un partage de fichiers. Ajoutez l'ID du partage de fichiers et les valeurs des balises au format « paire clé:valeur » dans le corps de la demande.  a| 
`ID`: L'ID du partage de fichiers.



 a| 
`METTRE'
 a| 
`/v2.1/fileshres/{id}'
| Vous pouvez modifier n'importe quel partage de fichiers en fonction de son ID. Ajoutez l'ID du serveur de fichiers et les valeurs que vous souhaitez modifier dans le corps de la demande, telles que le nom, le protocole, la stratégie d'instantané, la stratégie de sauvegarde et les balises.  a| 
`ID`: L'ID du partage de fichiers. `name`: Le nom du partage de fichiers. `mettre_gb`: La taille du partage de fichiers en GBs. `niveau_service`: Le nom du niveau de service s'applique: Standard, Premium, Premium-Tiering, Extreme ou Extreme-Tiering. `protocole`: Protocole utilisé pour accéder au partage de fichiers (NFS, CIFS ou multi-protocole). `export_policy': La politique d'exportation du partage de fichiers.



 a| 
`SUPPRIMER'
 a| 
`/v2.1/fileshres/{id}'
| Vous pouvez supprimer n'importe quel partage de fichiers par son ID.  a| 
`ID`: L'ID du partage de fichiers.



 a| 
`SUPPRIMER'
 a| 
`/v2.1/fileshres/{id}/``napshot/{name}'
| Vous pouvez supprimer tout instantané d'un partage de fichiers par l'ID du partage de fichiers et le nom de l'instantané.  a| 
`ID`: L'ID du partage de fichiers. `name`: Le nom du snapshot.

|===

NOTE: Pour les partages CIFS, l'ajout d'un caractère `$' à la fin du chemin de partage en fera un partage caché, par exemple `pathtomyhiddenshare$'.
