---
sidebar: sidebar 
permalink: seapiref_zones.html 
keywords: netapp, keystone, zones, 
summary: Zones Keystone 
---
= Zones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les méthodes répertoriées dans le tableau suivant pour créer, modifier et supprimer des zones. Pour plus d'informations sur les API qui vous permettent de récupérer des zones, reportez-vous à la section API d'administration (Consumer).

|===
| Méthode HTTP | Chemin | Description 


| «POST» | `/v2.1/zones` | Créer une nouvelle zone. 


| `METTRE' | `/v2.1/zones/{name}' | Modifier les détails d'une zone. 


| `SUPPRIMER' | `/v2.1/zones/{name}' | Supprimer une zone. 
|===


== Attributs de zone

Le tableau suivant répertorie les attributs de zone.

|===
| Attribut | Type | Description 


| `id' | Chaîne | identifiant unique de la zone. 


| `nom' | Chaîne | Nom de la zone. 


| `descriptions' | Chaîne | Description de la zone. 


| `nom_de_référence' | Chaîne | Nom de la région dans laquelle réside la zone. 
|===


== Récupérer toutes les zones

Utilisez la méthode indiquée dans le tableau suivant pour extraire toutes les zones ou un sous-ensemble de zones. Si vous spécifiez une région, seuls les magasins de blocs appartenant à ce locataire seront renverra.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/zones` | Récupérer les zones. | (Facultatif) Nom de région (chaîne) `offset' et `limit` – voir link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Pagination commune"] 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 2,
    "limit": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
....


== Récupérer une zone par nom

Utilisez la méthode indiquée dans le tableau suivant pour récupérer une zone par le nom de la zone.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `GET' | `/v2.1/zones/{name}' | Récupérer une zone par nom. | `Nom (chaîne)`: Nom de zone 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
}
....


== Créer une zone

Utilisez la méthode indiquée dans le tableau suivant pour créer une zone.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| «POST» | `/v2.1/zones` | Créer une nouvelle zone au sein d'une région. | Aucune 
|===
Attributs de corps de la demande requis : `name', `desodescription', `region_name'

*Exemple corps de la demande :*

....
{
  "name": "MyZoneName",
  "description": "DescriptionOfMyZone",
  "region_name": "MyRegionName"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "DescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


== Modifier une zone

Utilisez la méthode indiquée dans le tableau suivant pour modifier une zone.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `METTRE' | `/v2.1/zones{name}' | Modifier une zone identifiée par son nom. | `nom (chaîne)`: Nom de la zone. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
{
  "name": "MyZoneName",
  "description": "NewDescriptionOfMyZone"
}
....
*Exemple de corps de réponse :*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "NewDescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


== Supprimer une zone

Utilisez la méthode indiquée dans le tableau suivant pour supprimer une zone.

|===
| Méthode HTTP | Chemin | Description | Paramètres 


| `SUPPRIMER' | `/v2.1/zones{name}' | Supprimez une seule zone identifiée par son nom. Toutes les ressources de stockage d'une zone doivent d'abord être supprimées. | `nom (chaîne)`: Nom de la zone. 
|===
Attributs de corps de demande requis: `aucun'

*Exemple corps de la demande :*

....
none
....
*Exemple de corps de réponse :*

Aucun contenu à retourner lors d'une suppression réussie.
