---
sidebar: sidebar 
permalink: sewebiug_modify_a_disk.html 
keywords: netapp, keystone, modify, disk, 
summary: Keystone permet de modifier un disque 
---
= Modifier un disque
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez modifier le nom du disque, le mappage du groupe d'hôtes, le niveau de service, la capacité et la stratégie de snapshot. Cette méthode vous permet de déplacer vos disques vers différents niveaux de service, le cas échéant.

Le disque doit être en état opérationnel. Pour comprendre les États de volume et les étapes à suivre pour les rendre opérationnels, voir link:sewebiug_view_disks.html["Afficher les disques"] et link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["États de l'objet"]

.Étapes
. Afficher le link:sewebiug_view_disks.html#view-disks["Liste des disques"].
. Localisez le disque dans la liste et cliquez sur l'icône Modifier correspondant à ce disque. (Pour plus de détails sur l'utilisation des éléments dans les listes, voir link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Actions de vue de liste"]).
. Apportez les modifications nécessaires ; reportez-vous à la section link:sewebiug_create_a_new_disk.html["Créer un nouveau disque"] pour une description des champs.
. Cliquez sur *Done*. Cela crée un travail pour modifier le disque.


Modifier le disque est exécuté comme une tâche asynchrone. Vous pouvez :

* Vérifiez l'état du travail dans la liste des travaux. Pour plus d'informations sur le suivi des travaux, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["ici"].
* Une fois le travail terminé, vérifiez l'état du disque dans la liste disques.

