---
sidebar: sidebar 
permalink: sewebiug_add_a_subscribed_service.html 
keywords: netapp, keystone, add, cloud, service, 
summary: 'Keystone permet d"ajouter un service cloud' 
---
= Ajouter un service cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section explique comment ajouter un service cloud.

Le moteur de service NetApp prend en charge Azure NetApp Files.

.Avant de commencer
Vous avez besoin des informations concernant les services cloud, notamment des identifiants pour vous connecter au service. Les informations varient en fonction du type de service cloud.

.Étapes
. Sélectionnez *Cloud Services* dans le menu.
. Cliquez sur *Créer*.
. Sur la page Créer un service cloud, sélectionnez le type de service cloud, puis complétez les informations pertinentes pour ce type de service :
+
*Azure:*

+
.. Sélectionnez le sous-locataire.
.. Entrez un nom pour l'environnement de travail OCCM qui sera créé pour le service.
.. Entrez l'ID du répertoire Azure (tenant), l'ID du client Azure, le code secret du client Azure et le nom du service Cloud.


. Spécifiez les balises pour le service si nécessaire.
. Cliquez sur *Créer*.

