---
sidebar: sidebar 
permalink: sewebiug_create_an_object_storage_group.html 
keywords: netapp, keystone, create, object, storage, group, 
summary: Keystone crée un groupe de stockage objet 
---
= Créer un groupe de stockage objet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez cette méthode pour créer un nouveau groupe de stockage d'objets.

.Étapes
. Afficher le link:sewebiug_view_a_list_of_users.html#view-a-list-of-users["Liste des utilisateurs"].
. Assurez-vous que le sous-locataire correct est sélectionné et que l'affichage indique des groupes (et non des utilisateurs).
. Cliquez sur *Créer un groupe*.
. Dans la boîte de dialogue Créer un groupe, entrez le nom du groupe.
. Sélectionnez la règle S3 dans la liste.
. Cliquez sur *Créer*. Cela crée un travail pour créer le groupe avec les paramètres spécifiés.


La création d'un groupe de stockage d'objets est exécutée en tant que tâche asynchrone. Vous pouvez vérifier l'état du travail dans la liste des travaux. Pour plus d'informations sur le suivi des travaux, reportez-vous à la section link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["ici"].
