---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: Gestion des abonnements Keystone 
---
= Gestion des abonnements
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestion des abonnements inclut l'attribution de niveaux de service à votre abonnement NetApp Keystone et aux services d'abonnement des locataires, ou l'allocation et la modification des capacités aux niveaux de service à l'aide de l'interface du moteur de services NetApp.

Les services d'abonnement représentés par la relation entre les fournisseurs de services/partenaires et NetApp et les abonnements des locataires représentent la relation entre le fournisseur de services et ses locataires et sous-locataires (clients finaux). Lorsque les administrateurs NetApp ou GSSC créent des services d'abonnement Keystone pour les partenaires et les locataires, cela implique que l'allocation du stockage a été effectuée. Toutefois, à moins que les niveaux de service ne soient créés et que la capacité allouée correspondante ne soit complète, le stockage ne peut pas être consommé par les sous-locataires ou les clients finaux. Les administrateurs partenaires peuvent gérer le stockage pour leurs services d'abonnement Keystone et leurs abonnements aux locataires. Les administrateurs de locataires ne peuvent voir que les détails de l'abonnement aux locataires et les services pour leur propre location.



== Gérez les abonnements Keystone

Si vous êtes administrateur partenaire, vous pouvez afficher et gérer vos services d'abonnement Keystone à partir de *ABONNEMENTS* > *abonnements Keystone*. *Les abonnements Keystone* représentent les services d'abonnement Keystone créés par les administrateurs NetApp pour les partenaires. Les administrateurs partenaires peuvent afficher leurs services d'abonnement Keystone et créer des demandes de service pour :

* Augmentez la capacité d'un abonnement
* Ajouter un service à un abonnement (attribuer un niveau de service et de la capacité)


Les demandes de service sont reçues et traitées par l'équipe d'assistance.

Vous pouvez également afficher et gérer les services de protection des données et de protection avancée auxquels vous êtes abonné, dans des onglets séparés. Pour plus d'informations, reportez-vous à la section link:index.html#flex-subscription["Protection et protection des données avancées"].



=== Augmentez la capacité d'un abonnement

Ainsi, vous pouvez augmenter la capacité dédiée aux niveaux de service souscrits pour répondre aux besoins croissants.

.Étapes
. Sélectionnez l'abonnement pour lequel vous souhaitez augmenter la capacité dans le menu déroulant.
. Cliquez sur *augmenter la capacité* pour le niveau de service souhaité.
. Spécifiez la capacité (en Tio) requise.
. Cliquez sur *confirmer*.vous revenez à la page gérer les abonnements Keystone.
. Cliquez sur *soumettre les modifications*. Une demande de service est créée pour que GSSC augmente la capacité. Vous pouvez afficher et suivre la progression de la demande de service par le numéro de demande de service affiché dans un message. Pour plus d'informations sur le suivi, reportez-vous à la section link:sewebiug_track_a_service_request.html["Suivre une demande de service"].




=== Ajoutez un service à un abonnement

Vous pouvez ajouter un service à un abonnement. L'ajout d'un service inclut l'attribution d'un niveau de service à votre abonnement et la spécification de la capacité pour le même niveau de service.

Chaque abonnement peut avoir un de chaque niveau de service. Par exemple, si votre abonnement contient déjà un service Extreme et Standard, vous pouvez ajouter un service Premium ou Block.

.Étapes
. Sélectionnez le niveau de service que vous souhaitez ajouter à votre abonnement dans le menu déroulant.
. Cliquez sur *Ajouter service*.
. Sélectionnez le niveau de service auquel vous souhaitez vous abonner dans le menu déroulant, par exemple `Extreme-Tiering', puis ajoutez la capacité (en Tio) à laquelle vous souhaitez vous engager au niveau de service.
. Cliquez sur *confirmer*. Vous revenez à la page gérer les abonnements Keystone.
. Cliquez sur *soumettre les modifications*. Une demande de service est créée pour GSSC. Attribuez le niveau de service à votre abonnement. Vous pouvez afficher et suivre la progression de la demande de service par le numéro de demande de service affiché dans un message.


Pour plus d'informations sur le suivi, reportez-vous à la section link:sewebiug_track_a_service_request.html["Suivre une demande de service"].



== Gérez les abonnements aux locataires

Si vous êtes un administrateur partenaire, vous pouvez créer, afficher et mettre à jour vos abonnements de tenant à partir de *ABONNEMENTS* > *abonnements de tenant*. Si vous êtes un administrateur de tenant, vous ne pouvez afficher que les abonnements.



=== Créez et modifiez un abonnement de locataire

Vous pouvez créer de nouveaux abonnements pour vos locataires.

.Étapes
. Cliquez sur *Nouveau abonnement*.
. Spécifiez la région, la zone, la durée de l'abonnement, les plans tarifaires et d'autres détails. L'abonnement au locataire est attribué à un abonnement Keystone en fonction de la zone sélectionnée. En effet, chaque abonnement Keystone est lié à une zone.
+

NOTE: Vous ne pouvez pas créer d'abonnements se chevauchant. La date de début doit être au moins le jour suivant, car les abonnements commencent un jour avant la date de début spécifiée. De plus, il ne peut pas être plus de 30 jours à compter de la date du jour.

. Cliquez sur *Créer*.


Vous ne pouvez supprimer aucun abonnement. Vous pouvez uniquement modifier les abonnements de tenant existants et ajouter de nouveaux niveaux de service, augmenter la capacité d'engagement pour un niveau de service et ajouter des balises aux abonnements.

Si vous êtes administrateur partenaire, vous pouvez modifier les abonnements aux locataires. Vous pouvez ajouter de nouveaux niveaux de service à un abonnement et modifier les capacités des niveaux de service déjà ajoutés. Pour ajouter un nouveau niveau de service, procédez comme suit :

.Étapes
. Sélectionnez l'abonnement que vous souhaitez modifier en cliquant sur l'icône `+`.
. Sur la page *Ajouter un nouveau niveau de service à l'abonnement*, sélectionnez le nouveau niveau de service et ajoutez la capacité requise. Si le niveau de service est déjà ajouté, vous ne pouvez pas l'ajouter ou le supprimer.
. Cliquez sur *mettre à jour*.


Vous pouvez également ajouter des balises en cliquant sur l'icône balises de l'abonnement.

Pour modifier les capacités souscrites aux niveaux de service déjà affectés à l'abonnement, procédez comme suit :

.Étapes
. Cliquez sur l'icône `v` pour développer l'abonnement que vous souhaitez modifier. Les niveaux de service de cet abonnement sont affichés.
. Sélectionnez le niveau de service que vous souhaitez modifier en cliquant sur l'icône correspondante.
. Modifiez le plan tarifaire en augmentant ou en diminuant la capacité en Tbs.
. Cliquez sur *mettre à jour*.

