---
sidebar: sidebar 
permalink: sewebiug_managing_azure_capacity_pools.html 
keywords: netapp, keystone, managing, azure, capacity, pools, 
summary: Gestion des pools de capacité Azure par Keystone 
---
= Gestion des pools de capacité Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section explique comment gérer les pools de capacité Azure :


NOTE: La gestion des pools de capacité Azure requiert un accès administrateur client.

Cette section décrit comment effectuer les tâches suivantes :

* Afficher la liste des pools de capacité Azure
* Ajoutez un pool de capacité Azure
* Modifier les détails du pool de capacité Azure
* Supprimez un pool de capacité Azure




=== Afficher la liste des pools de capacité Azure

La liste pools de capacité Azure affiche une liste de pools de capacité pour un sous-locataire et un emplacement spécifiés. Pour afficher la liste, sélectionnez *SERVICES DE FICHIERS > Azure Capacity pools* dans le menu.

La liste affiche des informations simples sur chaque pool de capacité Azure. Les icônes d'action en regard de chaque pool de capacité Azure vous permettent de modifier ou de supprimer le pool de capacité Azure.



=== Ajoutez un pool de capacité Azure

Cette section décrit l'ajout d'un pool de capacité Azure.

Vous aurez besoin des éléments suivants :

* Sous-locataire auquel appartient la capacité
* Le compte ANF
* Le niveau de service
* Un nom pour le pool de capacité
* La taille du pool


.Étapes
. Sélectionnez *SERVICES DE FICHIERS > Azure Capacity pools* dans le menu.
. Cliquez sur *Créer*.
. Dans la boîte de dialogue Créer un pool de capacité Azure, spécifiez le sous-locataire, le compte ANF, le niveau de service, le nom et la taille.
. Ajoutez des balises au pool de capacité si nécessaire.
. Cliquez sur *Créer*. Lorsque le pool de capacités est créé, l'état devient `séparé` (peut être affiché dans la liste des pools de capacité Azure).




=== Modifier les détails du pool de capacité Azure

Utilisez cette méthode pour modifier les détails d'un pool de capacité Azure. Vous pouvez modifier le niveau de service de la taille du pool et ajouter ou supprimer des balises.

.Étapes
. Sélectionnez *SERVICES DE FICHIERS > Azure Capacity pools* dans le menu.
. Dans la liste, recherchez le pool de capacité Azure et cliquez sur l'icône de modification.
. Dans la boîte de dialogue Manage Azure Capacity Pool, apportez les modifications nécessaires.
. Cliquez sur *mettre à jour*.




=== Supprimez un pool de capacité Azure

Utilisez cette méthode pour supprimer un pool de capacité Azure.

.Étapes
. Sélectionnez *SERVICES DE FICHIERS > Azure Capacity pools* dans le menu.
. Dans la liste, recherchez le pool de capacité Azure et cliquez sur l'icône de suppression.
. Dans la boîte de dialogue confirmer la suppression, entrez le nom du pool de capacité Azure à supprimer.
. Cliquez sur *confirmer*.

