---
sidebar: sidebar 
permalink: sewebiug_view_disks.html 
keywords: netapp, keystone, view, buckets, 
summary: Disques avec vue Keystone 
---
= Afficher les disques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La liste disques affiche les disques appartenant au tenant sélectionné. Pour afficher la liste, sélectionnez *STOCKAGE BLOC > disques* dans le menu.

Les disques qui font déjà partie de votre environnement existant et appartiennent aux VM de stockage configurées dans votre moteur de services NetApp peuvent également être affichés sur cet écran et gérés dans le cadre de vos services d'abonnement NetApp Keystone. Les disques provisionnés en dehors du moteur de service NetApp sont régulièrement importés et répertoriés sur cette page avec les codes d'état appropriés.

Si les disques importés respectent des normes acceptables du moteur de services NetApp, c'est-à-dire si tous les paramètres nécessaires à la mise en service des disques sont disponibles, ils sont importés avec le statut `opérationnel' et peuvent être directement gérés via NetApp Service Engine. Cependant, certains disques peuvent ne pas être de la même norme que les disques existants sur le moteur de services NetApp. Après importation, ces disques sont classés avec le statut «importé» ou «non standard». Pour connaître les États des disques et les étapes à suivre pour les rendre opérationnels, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["États de l'objet"]

Dans la liste des disques, affichez des informations simples. Pour plus d'informations sur l'utilisation des fonctions d'une liste, voir link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Actions de vue de liste"].

* Nom du disque
* Chemin d'accès au disque
* Taille du disque
* Protocole
* Sous-locataire auquel appartient le disque
* Zone dans laquelle le disque existe
* État opérationnel

