---
sidebar: sidebar 
permalink: sewebiug_alerts.html 
keywords: netapp, keystone, alert, create, custom alert 
summary: Création et gestion des alertes 
---
= Création et gestion des alertes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les alertes sont des messages déclenchés automatiquement ou créés manuellement pour partager des informations sur les événements critiques de votre environnement.

Lorsque vous provisionnez le stockage, des alertes automatiques sont déclenchées dans les scénarios suivants :

* Le nouveau disque ou le partage de fichiers pousse l'abonnement en rafale
* Le nouveau disque ou partage de fichiers est configuré sur un nouvel abonnement
* La capacité consommée dans l'abonnement a dépassé le seuil de capacité défini ou se situe à proximité de la capacité engagée


L'écran *alertes* vous permet d'afficher les alertes générées par le système et générées par l'utilisateur dans votre environnement.

Vous pouvez également créer des alertes personnalisées et les afficher à d'autres utilisateurs. Ils peuvent afficher et rejeter les alertes pour eux-mêmes et pour d'autres utilisateurs de leur location, le cas échéant.



== Créez une alerte dans votre environnement mutualisé

Si vous êtes administrateur partenaires, vous pouvez créer et envoyer manuellement des alertes à un seul locataire ou à tous les locataires de votre environnement.


NOTE: Vous pouvez rejeter une alerte que vous avez créée. Toutefois, elle n'est rejetée que pour les locataires qui ne l'ont pas encore vu.

.Étapes
. Sélectionnez *ADMINISTRATION* > *alertes* dans le menu.
. Cliquez sur *Créer alerte*.
. Sur l'écran *Créer une alerte*, sélectionnez l'état et le locataire auquel vous souhaitez envoyer l'alerte, puis ajoutez le message.
+

NOTE: Si vous souhaitez envoyer l'alerte à tous les locataires de votre environnement, sélectionnez « tous ».

. Cliquez sur *Créer*. La nouvelle alerte est créée.




== Créer une alerte dans votre location

Si vous êtes un administrateur de tenant, vous pouvez créer et envoyer manuellement des alertes à tous les utilisateurs de votre environnement.


NOTE: Vous pouvez rejeter une alerte que vous avez créée. Pourtant, elle est rejetée uniquement pour les utilisateurs qui ne l'ont pas encore vu.

.Étapes
. Sélectionnez *ADMINISTRATION* > *alertes* dans le menu.
. Cliquez sur *Créer alerte*.
. Sur l'écran *Créer alerte*, sélectionnez l'état et ajoutez le message.
. Cliquez sur *Créer*. La nouvelle alerte est créée.

