---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_group.html 
keywords: netapp, keystone, modify, object, storage, group 
summary: Keystone permet de modifier un groupe de stockage objet 
---
= Modifier un groupe de stockage d'objets
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez cette méthode pour modifier les détails d'un groupe de stockage objet, comme le nom du groupe et la règle S3.

.Étapes
. Afficher le Storage Group d'objets link:sewebiug_view_the_object_storage_group_and_users.html["Afficher les utilisateurs et les groupes de stockage objet"].
. Assurez-vous que le sous-locataire correct est sélectionné et que vous avez cliqué sur l'onglet *groupes*.
. Recherchez le groupe dans la liste et cliquez sur l'icône de modification correspondant à ce groupe.
+
Pour plus d'informations sur l'utilisation des éléments dans les listes, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Actions de vue de liste"].

. Dans la boîte de dialogue *Modifier le groupe*, modifiez la stratégie S3 applicable au groupe. Pour plus d'informations sur les règles S3, reportez-vous à la section https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy["Spécifiez les autorisations dans une stratégie"].
. Vous pouvez ajouter des énoncés de police supplémentaires si nécessaire.
. Cliquez sur *mettre à jour*. Cela crée un travail pour modifier le groupe avec les paramètres spécifiés. Pour plus d'informations sur le suivi des travaux, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["ici"].

