---
sidebar: sidebar 
permalink: sewebiug_create_a_disk_from_a_snapshot.html 
keywords: netapp, keystone, create, disk, snapshot 
summary: 'Créer un disque à partir d"un snapshot' 
---
= Créer un disque à partir d'un snapshot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer un nouveau disque à partir d'un snapshot existant. Le nouveau disque, cloné à partir du snapshot, a les mêmes propriétés que le disque à partir duquel le snapshot est créé.

.Étapes
. Sélectionnez *BLOCK STORAGE* dans le volet de navigation de gauche et sélectionnez *Disks*. La liste des disques existants pour votre location s'affiche.
. Cliquez sur *Créer disque* et sélectionnez *Cloner à partir de snapshot*. Si vous connaissez le disque dont vous souhaitez utiliser le snapshot pour le clonage, vous pouvez également localiser le disque et cliquer sur le bouton de copie situé en regard de celui-ci. Le disque doit être en état opérationnel. L'écran *Créer disque à partir de snapshot* s'affiche avec tous les disques du tenant. Vous pouvez filtrer les disques par région, zone et sous-locataire. Vous pouvez sélectionner n'importe quel disque qui est à l'état opérationnel. Pour plus d'informations sur l'état d'un objet, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["États de l'objet"]
. Cochez la case en regard du disque souhaité et cliquez sur *Suivant*. Les instantanés du disque sont affichés.
+

NOTE: Pour le disque sélectionné, si certains snapshots sont créés dans votre environnement SnapCenter en dehors du moteur de service NetApp, vous pouvez les importer et les lister pour votre sélection. Vous pouvez sélectionner ces instantanés importés et cloner les nouveaux disques.

+
Vous pouvez rechercher un snapshot particulier ou sélectionner le type de planification pour filtrer les snapshots.

. Cochez la case située en regard du snapshot à cloner et cliquez sur *Suivant*. Le nouveau disque hérite des propriétés du snapshot sélectionné.
. Ajoutez *Nom* et *chemin de disque*. Mettez à jour les autres paramètres, tels que l'attribution d'un *niveau de service*, puis cliquez sur *Créer*. Sélectionnez le niveau de service qui correspond le mieux à vos besoins. .Une fois que vous avez terminé


*Create Disk* est exécuté en tant que travail asynchrone. Vous pouvez :

* Vérifiez l'état du travail dans la liste des travaux. Pour plus d'informations sur le suivi des travaux, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["ici"].
* Une fois le travail terminé, vérifiez l'état du disque dans la liste *disques*.

