---
sidebar: sidebar 
permalink: sewebiug_create_adhoc_snapshot_of_a_file_share.html 
keywords: netapp, keystone, create, adhoc, snapshot, file, share, 
summary: 'Keystone crée un snapshot ad hoc d"un partage de fichiers' 
---
= Créer un instantané ad hoc d'un partage de fichiers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section décrit comment créer un instantané ad hoc d'un partage de fichiers.

.Étapes
. Afficher le link:sewebiug_view_shares.html#view-shares["Liste des partages"].
. Localisez le partage dans la liste et cliquez sur l'icône d'instantané correspondant à ce partage. (Pour plus de détails sur l'utilisation des éléments dans les listes, voir link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Actions de vue de liste"].
. Dans la boîte de dialogue Créer un instantané, entrez un nom pour votre instantané et cliquez sur *Créer*.


.Une fois que vous avez terminé
Cette disponibilité peut prendre quelques minutes. Si disponible, vous pouvez créer un autre partage en clonant ce snapshot. Pour plus d'informations, reportez-vous à la section link:sewebiug_create_file_share_from_snapshot.html["Créez un partage de fichiers à partir d'un instantané"].
