---
sidebar: sidebar 
permalink: sewebiug_add_a_user.html 
keywords: netapp, keystone, add, user, 
summary: Keystone ajoute un utilisateur 
---
= Ajouter un utilisateur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section décrit comment ajouter un utilisateur.

.Avant de commencer
Éléments requis :

* Les locataires auxquels l'utilisateur doit avoir accès.
* Rôle auquel l'utilisateur doit être accordé au sein de chaque location. Un utilisateur ne peut avoir qu'un seul rôle au sein d'une location.


.Étapes
. Sélectionnez *ADMINISTRATION > utilisateurs* dans le menu.
. Cliquez sur *Créer un utilisateur*.
. Dans la boîte de dialogue Créer un utilisateur, indiquez le nom d'utilisateur, l'adresse e-mail, le prénom, le nom, le nom d'affichage, et le mot de passe de l'utilisateur.
. Sélectionnez le locataire principal et le rôle de l'utilisateur dans cette location.
+

NOTE: Vous pouvez attribuer des privilèges à un utilisateur en fonction de son rôle, par exemple un administrateur NetApp ou l'administrateur NetApp avec des privilèges en lecture seule, un administrateur partenaire ou un administrateur locataire. En fonction de votre rôle, vous pouvez afficher les rôles des différents utilisateurs au sein de votre environnement et attribuer des rôles aux nouveaux utilisateurs ou aux utilisateurs existants.

. Pour ajouter des locations supplémentaires, cliquez sur *Ajouter une location* pour afficher de nouveaux champs de saisie et sélectionnez le locataire et le rôle de l'utilisateur dans cette location.
. Cliquez sur *Créer*.

