---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: Partenaire moteur de service NetApp, fonctions du fournisseur de services 
---
= Rôles et opérations des fournisseurs de services et des clients
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En fonction de votre rôle de fournisseur de services ou de partenaire (utilisé de manière interchangeable) ou d'un administrateur client ou locataire (utilisé de manière interchangeable), les vues et fonctions du portail Web NetApp Service Engine sont déterminées.



== Activités pouvant être réalisées en tant qu'administrateur de fournisseur de services

En tant qu'administrateur de fournisseurs de services dans un environnement mutualisé, vous pouvez effectuer les fonctions de provisionnement, de création de rapports, de facturation et de gestion des clients possédant leurs propres abonnements, via l'interface utilisateur Web du moteur de services NetApp. Vous pouvez effectuer les opérations suivantes :

* Afficher le stockage souscrit et provisionné dans le cadre de leur service Flex Subscription.
+

NOTE: À titre de prestation de services, vous pouvez vendre plus de capacité à vos clients qu'à l'achat de services de NetApp (sursouscription). Les abonnements aux locataires peuvent s'étendre au-delà de la période d'abonnement Flex actuelle, mais un avertissement s'affiche au moment de la création de l'abonnement et dans les tableaux de bord/rapports.

* Créer, afficher, modifier et supprimer des locataires, sous-locataires, et aux utilisateurs.
* Afficher les zones et les régions de vos abonnements.
* Gérez et hébergez plusieurs locataires dans le service Flex Subscription : créez et gérez les abonnements des locataires et consultez vos propres détails d'abonnement Flex.
+

NOTE: Les abonnements locataires peuvent être créés en fonction des zones correspondantes et des abonnements Keystone Flex. Elles sont créées selon les niveaux de service fournis sous la capacité souscrite de votre abonnement Flex.

* Créez des serveurs de fichiers ou des magasins de blocs et initialisez le stockage en mode bloc, fichier et objet, comme vous le savez, des exigences réseau pour provisionner chaque type de stockage pour vos locataires.
* Vous pouvez également créer et gérer des sous-réseaux pour vos locataires,
* Afficher les partages de fichiers, les disques et les compartiments créés dans le cadre de votre abonnement Flex. La création et la gestion des groupes de stockage objet ainsi que des utilisateurs.
* Créez des rapports de consommation sur votre abonnement NetApp Keystone Flex et sur vos abonnements aux locataires, ainsi que sur leur utilisation pour tous les locataires, pour l'utiliser dans les systèmes de facturation et de notation respectifs.
* Affichez la facturation et le reporting pour tous les locataires et clients, et pour l'espace de stockage souscrit ou provisionné uniquement.
* Afficher et gérer les demandes de service émises par les clients dans votre propre outil de demande de service (intégré à OpsRamp/GSSC).




== Activités pouvant être réalisées en tant qu'administrateur client/locataire

En tant qu'administrateur de tenant, vous pouvez afficher les détails de l'abonnement de votre propre location et exécuter des tâches administratives pour vos sous-locataires. Vous pouvez effectuer les opérations suivantes :

* Affichez le stockage souscrit et provisionné dans le cadre de votre service d'abonnement aux locataires.
* Gérez et modifiez les sous-locataires de votre location.
* Affichez vos zones, régions, sous-locataires et sous-réseaux.
* Afficher les serveurs de fichiers créés par les fournisseurs de services.
* Créer des partages de fichiers, des disques et des compartiments, et leur attribuer des niveaux de service.
* Affichez les rapports des locataires et sous-locataires à partir de *Rapports > utilisation de la capacité* pour afficher les données de consommation uniquement pour le stockage auquel vous êtes abonné ou provisionné pour votre location et vos sous-locataires.
* Consultez les rapports des locataires et du sous-locataire de *Rapports > performances* pour afficher les performances et la conformité des services de votre location pour chaque service souscrit et services complémentaires (protection des données et protection avancée).
+

NOTE: Pour les abonnements supplémentaires, vous pouvez utiliser votre outil de demande de service.


