---
sidebar: sidebar 
permalink: sewebiug_managing_azure_netapp_accounts.html 
keywords: netapp, keystone, managing, azure, accounts, 
summary: Gestion des comptes Azure NetApp 
---
= Gestion des comptes Azure NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section explique comment gérer des comptes Azure NetApp :


NOTE: La gestion des comptes Azure NetApp requiert un accès administrateur client.

Dans cette section :

* Consultez la liste des comptes Azure NetApp
* Ajoutez un compte Azure NetApp
* Modifier les détails du compte Azure NetApp
* Supprimez un compte Azure NetApp




== Consultez la liste des comptes Azure NetApp

La liste pour les comptes Azure NetApp affiche la liste de tous les comptes Azure NetApp pour les locations auxquelles l'utilisateur connecté a accès. Pour afficher la liste, sélectionnez *ADMINISTRATION > comptes Azure NetApp* dans le menu.

La liste affiche des informations simples sur chaque compte Azure NetApp. Les icônes d'action affichées à côté de chaque compte Azure NetApp vous permettent de modifier ou de supprimer le compte Azure NetApp.



== Ajoutez un compte Azure NetApp

Cette section explique comment ajouter un compte Azure NetApp.

.Avant de commencer
Vous aurez besoin des éléments suivants :

* Sous-locataire auquel appartient le compte Azure NetApp
* Instance ANF
* Emplacement Azure (région)
* Groupe de ressources Azure
* Un nom pour le compte


.Étapes
. Sélectionnez *ADMINISTRATION > comptes Azure NetApp* dans le menu.
. Cliquez sur *Créer*.
. Dans la boîte de dialogue Créer un compte NetApp Azure, indiquez le sous-locataire, l'emplacement Azure (région), le groupe de ressources Azure et un nom pour le compte Azure NetApp.
. Si nécessaire, ajoutez des balises au compte.
. Cliquez sur *Créer*. Une fois la création réussie, l'état du compte est réussi (peut être affiché dans la liste des comptes Azure NetApp).




== Modifiez les balises de compte Azure NetApp

Utilisez cette méthode pour modifier les balises associées à un compte Azure NetApp.

.Étapes
. Sélectionnez *ADMINISTRATION > comptes Azure NetApp* dans le menu.
. Recherchez le compte Azure NetApp dans la liste et cliquez sur l'icône Modifier.
. Dans la boîte de dialogue Manage Azure NetApp Account, ajoutez, supprimez ou modifiez les balises selon vos besoins.
. Cliquez sur *mettre à jour*.




== Supprimez un compte Azure NetApp

Utilisez cette méthode pour supprimer un compte Azure NetApp.

.Étapes
. Sélectionnez *ADMINISTRATION > comptes Azure NetApp* dans le menu.
. Recherchez le compte Azure NetApp dans la liste et cliquez sur l'icône de suppression.
. Dans la boîte de dialogue confirmer la suppression, entrez le nom du compte Azure NetApp à supprimer.
. Cliquez sur *confirmer*.

