---
sidebar: sidebar 
permalink: sewebiug_view_shares.html 
keywords: netapp, keystone, view, shares, 
summary: Partages de vues Keystone 
---
= Afficher les partages de fichiers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La liste *partages* affiche les partages de fichiers appartenant au locataire sélectionné. Pour afficher la liste, sélectionnez *SERVICES DE FICHIERS > partages* dans le menu.

Les partages de fichiers qui font déjà partie de votre environnement existant et qui font partie des machines virtuelles de stockage configurées dans votre moteur de service NetApp, peuvent également être affichés sur cet écran et gérés comme faisant partie de vos services NetApp Keystone Flex Subscription (Flex Subscription). Les partages de fichiers provisionnés en dehors du moteur de services NetApp sont régulièrement importés et répertoriés sur cette page avec les codes d'état appropriés.

Si les partages de fichiers importés sont dans des normes acceptables de NetApp Service Engine, c'est-à-dire tous les paramètres nécessaires à la mise en service des partages sont disponibles, ils sont importés avec le statut `opérationnel' et peuvent être directement gérés via NetApp Service Engine. Cependant, il est possible que certains partages ne soient pas conformes à la même norme que les partages existants sur NetApp Service Engine. Après l'importation, ces partages de fichiers sont classés avec le statut «importé» ou «non standard». Pour comprendre les États de volume et les étapes à suivre pour les rendre opérationnels, voir link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["États de l'objet"]

La liste partages affiche des informations simples sur chaque partage. Pour plus d'informations sur l'utilisation des fonctions d'une liste, voir link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Vue liste"].

* Nom de partage
* Serveur sur lequel il réside
* Chemin du partage
* Chemin de partage CIFS (utilisé pour le montage du partage CIFS avec l'intégration DNS)
* Sous-locataire auquel il appartient
* Zone dans laquelle elle existe
* Niveau de service
* État opérationnel (fonctionnement, mise à jour ou contact du support)
* Date de création

