---
sidebar: sidebar 
permalink: sewebiug_view_host_groups.html 
keywords: netapp, keystone, view, host, groups, 
summary: 'Vue des groupes d"hôtes Keystone' 
---
= Travailler avec des groupes hôtes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les groupes d'hôtes sont définis pour déterminer l'accès aux disques. En fonction des nœuds d'initiateur affectés à un groupe d'hôtes, l'accès à ce groupe est déterminé. Vous pouvez ajouter des initiateurs lors de la création du groupe hôte.



== Afficher les groupes d'hôtes

Pour afficher la liste Groupe d'hôtes, sélectionnez *STOCKAGE BLOC > groupes d'hôtes* dans le menu.

La liste affiche les groupes d'hôtes définis.

À partir de cette page, vous pouvez créer un nouveau groupe d'hôtes, modifier un groupe d'hôtes et supprimer un groupe d'hôtes.



= Créez un groupe d'hôtes

Il existe deux façons de créer un groupe d'hôtes :

* À partir de la page groupes d'hôtes, décrite ci-dessous.
* Dans le cadre de la création d'un nouveau disque. Utilisez cette méthode lorsque vous devez créer un groupe d'hôtes sur un magasin de blocs qui n'a pas encore été initialisé. Pour plus d'informations, voir link:sewebiug_create_a_new_disk.html#create-a-new-disk["Créer un nouveau disque"].
+
Il est possible de créer un groupe d'hôtes vide et de le mapper sur un disque en tant qu'espace réservé. Vous devez mettre à jour le groupe d'hôtes vide pour ajouter des initiateurs avant de pouvoir accéder au stockage.



.Avant de commencer
Vous devez disposer des éléments suivants pour créer le groupe d'hôtes :

* Le sous-locataire, la région et la zone dans lesquelles créer le groupe hôte.



NOTE: Si le magasin de blocs d'une combinaison de sous-tenant/zone n'a pas été initialisé au préalable, vous ne pourrez pas créer un groupe d'hôtes à l'aide de cette méthode. Une alternative est de suivre le link:sewebiug_create_a_new_disk.html#create-a-new-disk["Créer un nouveau disque"] processus, qui vous permet d'initialiser le magasin de blocs et de créer un groupe d'hôtes dans le cadre du processus.

* Un nom pour le groupe hôte
* Protocole du groupe d'hôtes : iSCSI ou FCP
* La liste des initiateurs à ajouter au groupe : WWPN pour les nœuds hôtes FC ou IQN pour les noms de nœuds hôtes iSCSI.
* Un alias pour chaque initiateur ; un alias est un nom simple pour identifier le serveur initiateur ou un port/interface individuel sur le serveur. Par exemple, Server 4.


.Étapes
. link:sewebiug_view_host_groups.html#view-host-groups["Afficher les groupes d'hôtes"] liste.
. Cliquez sur *Créer un groupe d'hôtes*.
. Sur la page Créer un groupe d'hôtes :
+
.. Sélectionnez le protocole : iSCSI ou FCP.
.. Sélectionnez le sous-locataire, la région et la zone et pour le groupe d'hôtes.


. Spécifiez un nom pour le groupe d'hôtes.
. Sélectionnez le type de système d'exploitation : le système d'exploitation sur disque.
. Ajoutez les initiateurs du groupe. Pour chaque initiateur, spécifiez l'alias et l'initiateur.
. Si nécessaire, ajoutez des balises (paires clé-valeur) au groupe d'hôtes dans la section Etiquettes.
. Cliquez sur *Créer*. Ceci crée le groupe hôte.


.Une fois que vous avez terminé
Une fois le groupe d'hôtes créé, il est disponible pour le mappage sur des disques.



== Modifier des groupes d'hôtes

Vous pouvez modifier un groupe d'hôtes pour ajouter, supprimer ou modifier des initiateurs.

.Notez ces points :
* Vous ne pouvez pas modifier le groupe d'hôtes si le groupe d'hôtes n'est pas opérationnel et si l'icône Modifier le stylet est désactivée pour ces groupes.
* La modification d'un groupe d'hôtes modifie l'accès de chaque disque mappé au groupe d'hôtes.
* Vous ne pouvez pas modifier l'alias d'un initiateur. Pour modifier l'alias, supprimez l'initiateur du groupe, puis recréez-le.


.Étapes
. Afficher le link:sewebiug_view_host_groups.html#view-host-groups["Groupes d'hôtes"] liste.
. Recherchez le groupe d'hôtes dans la liste, faites défiler jusqu'à la fin de la ligne, puis cliquez sur l'icône Modifier (icône en forme de stylo) correspondant à ce groupe d'hôtes.
+
Pour modifier un initiateur existant, recherchez-le dans la liste, modifiez-le et cliquez sur *Update*.

+
Pour ajouter un initiateur :

+
.. Cliquez sur *Ajouter initiateur*.
.. Spécifiez l'alias et l'initiateur.
.. Cliquez sur *Créer*.
+
Pour supprimer un initiateur du groupe hôte, recherchez-le dans la liste et cliquez sur l'icône Supprimer.



. Cliquez sur *Fermer*.




== Supprimer un groupe d'hôtes

Vous pouvez supprimer un groupe d'hôtes s'il n'y a aucun disque mappé sur le groupe d'hôtes.

.Étapes
. Afficher le link:sewebiug_view_host_groups.html#view-host-groups["Groupes d'hôtes"] liste.
. Recherchez le groupe d'hôtes dans la liste et cliquez sur l'icône Supprimer pour ce groupe d'hôtes.
. Dans la boîte de dialogue confirmer la suppression, entrez le nom du groupe d'hôtes pour confirmer la suppression du groupe d'hôtes.
. Cliquez sur *confirmer*.

