---
sidebar: sidebar 
permalink: sewebiug_getting_started_overview.html 
keywords: netapp, keystone, getting, started, overview, 
summary: Présentation de la mise en route de Keystone 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section décrit comment utiliser le portail Service Engine de NetApp.


NOTE: Lorsque vous naviguez sur le portail NetApp Service Engine, vous pouvez constater que certaines informations, telles que votre région et votre zone, sont automatiquement renseignées en fonction de la configuration de votre abonnement configurée par l'équipe du support.

Pour commencer vos activités sur ce portail :

* Connectez-vous à l'interface Web du moteur de services NetApp.
+
** Connectez-vous avec un nom d'utilisateur et un mot de passe
** Pour plus d'informations, connectez-vous avec NetApp SSO. Consultez link:sewebiug_log_in_to_the_netapp_service_engine_web_interface.html["Connectez-vous à l'interface Web du moteur de services NetApp"]


* Sélectionnez le locataire. Le tableau de bord s'affiche. Pour plus d'informations, reportez-vous à la section link:sewebiug_dashboard.html["Afficher le tableau de bord des abonnements Flex"]


Pour en savoir plus sur l'interface Web du moteur de service NetApp, consultez la section link:sewebiug_netapp_service_engine_web_interface_overview.html["Présentation de l'interface Web du moteur de service NetApp"]
