---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, Snapshot 
summary: 'Créer un partage de fichiers à partir d"un instantané' 
---
= Créer un partage de fichiers à partir d'un instantané
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer un nouveau partage de fichiers à partir d'un snapshot existant. Le nouveau partage de fichiers, cloné à partir de la copie Snapshot, a les mêmes propriétés que le partage de fichiers à partir duquel la copie Snapshot est créée.

.Étapes
. Sélectionnez *SERVICES DE FICHIERS* dans le volet de navigation de gauche et sélectionnez *partages*.
. Cliquez sur *Créer un partage* et sélectionnez *Cloner à partir de snapshot*. L'écran *Select Share* s'affiche avec tous les partages de fichiers pour le locataire. Vous pouvez filtrer les partages de fichiers par région, zone et sous-locataire. Vous pouvez sélectionner n'importe quel partage de fichiers à l'état opérationnel.
. Cochez la case en regard du partage de fichiers souhaité et cliquez sur *Suivant*. L'écran *Sélectionner instantané* s'affiche avec tous les instantanés du partage de fichiers.
+

NOTE: Pour le partage de fichiers sélectionné, si certains snapshots sont créés dans votre environnement SnapCenter à l'extérieur du moteur de service NetApp, vous pouvez les trouver importés et répertoriés dans le pour votre sélection. Vous pouvez sélectionner ces snapshots importés et cloner les nouveaux partages de fichiers à partir d'eux.

+
Vous pouvez rechercher un snapshot particulier ou sélectionner le type de planification pour filtrer les snapshots.

. Cochez la case en regard du snapshot à partir lequel vous souhaitez cloner et cliquez sur *Suivant*. Le nouveau partage de fichiers hérite des propriétés du snapshot sélectionné.
. Ajouter *Nom* et *chemin de partage*. Mettez à jour les autres paramètres, tels que l'attribution d'un *niveau de service*, puis cliquez sur *Créer*.


.Une fois que vous avez terminé
* Pour les partages de type CIFS uniquement : pour rendre les partages disponibles par nom d'hôte, votre administrateur de domaine doit mettre à jour les enregistrements DNS avec le nom du serveur CIFS et l'adresse IP. Dans le cas contraire, le partage n'est accessible que via l'adresse IP. Par exemple :
+
** Lorsque les enregistrements DNS sont mis à jour, utilisez le nom d'hôte ou l'adresse IP pour accéder au partage, par exemple file://hostname/share["\\hostname\share"^] ou file://IP/share["\\IP\share"^]
** En l'absence d'enregistrement DNS mis à jour, vous devez utiliser l'adresse IP pour accéder au partage, c'est-à-dire file://IP/share["\\IP\share"^]


* *Créer un partage* est exécuté en tant que travail asynchrone. Vous pouvez :
+
** Vérifiez l'état du travail dans la liste des travaux. Pour plus d'informations sur le suivi des travaux, reportez-vous à la section link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["ici"].
** Une fois le travail terminé, vérifiez l'état du partage dans la liste *partages*.



