---
sidebar: sidebar 
permalink: sewebiug_working_with_object_storage_overview.html 
keywords: netapp, keystone, working, object, storage, overview, 
summary: Présentation de Keystone avec le stockage objet 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le stockage objet requiert un abonnement au service de stockage objet. Lorsqu'un service de stockage objet est disponible dans le cadre de l'abonnement, le stockage doit être initialisé avant de pouvoir être utilisé.

Avec le stockage objet, les objets sont stockés dans des compartiments S3. L'accès aux compartiments S3 est géré à l'aide d'autorisations définies sur des groupes de stockage d'objet. Les utilisateurs de stockage objet sont affectés à un ou plusieurs groupes de stockage objet, héritant des autorisations de l'appartenance au groupe.

Chaque utilisateur du stockage objet dispose de clés S3 qui permettent d'accéder au stockage objet.


NOTE: L'accès au stockage objet s'effectue via un navigateur compatible S3.

Cette section décrit comment gérer le stockage objet :

* Initialiser le stockage d'objets.
* Création de compartiments S3.
+
Il n'est pas possible de supprimer des compartiments S3 via le portail Web de NetApp Service Engine ; supprimez ces compartiments à l'aide d'un navigateur compatible S3.

* Créez et gérez des groupes de stockage d'objets.
* Créez et gérez les utilisateurs du stockage objet, notamment la création de clés S3.

