---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: Créer, modifier et supprimer des sauvegardes ou des restaurations à partir de sauvegardes 
---
= Sauvegarder les partages de fichiers et les disques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez définir des stratégies de sauvegarde pour créer des sauvegardes des volumes (partages de fichiers et disques) de votre environnement et conserver à distance plusieurs copies des volumes primaires.


NOTE: Les sauvegardes sont automatiquement créées sur votre système lorsque vous créez ou modifiez une stratégie de sauvegarde pour un volume. Vous ne pouvez pas créer de sauvegarde à partir de l'interface du moteur de services NetApp. Vous pouvez utiliser l'API backups pour créer et gérer des sauvegardes pour vos volumes.

Pour plus d'informations, reportez-vous à la section link:seapiref_backups_apis.html["API de sauvegarde"]

La sauvegarde de vos volumes source est activée via la technologie NetApp SnapMirror activée dans votre abonnement Flex. Pour plus d'informations, reportez-vous à la section link:index.html#flex-subscription["ici"].

Lorsque vous créez ou modifiez un volume, vous définissez sa planification de sauvegarde. La sauvegarde est effectuée aux intervalles prévus et stockée sur un système de destination. Pour que les sauvegardes fonctionnent, la relation SnapMirror doit être établie avec l'environnement de destination. Les partages de fichiers répliqués et les disques de différentes zones sont stockés sur une VM de stockage de sauvegarde dédiée (SVM, également appelée Storage Virtual machine) sur chaque cluster. Les sauvegardes peuvent être réalisées entre deux clusters ONTAP distincts dans des zones différentes.

Les règles de sauvegarde standard prises en charge par le moteur de service NetApp sont les suivantes :

* Ad hoc
* Tous les jours
* Hebdomadaire
* Tous les mois


Pour les sauvegardes créées en back-end, vos volumes doivent être à l'état « opérationnel ». Pour plus d'informations sur l'état d'un objet, reportez-vous à la section opérationnel (pour l'objet source d'une sauvegarde). link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["ici"].

Si votre volume ne respecte pas les règles de sauvegarde standard prises en charge par le moteur de services NetApp, vous pouvez link:sewebiug_raise_a_service_request.html["demander un service"] De la catégorie *Volume non standard* pour résoudre le problème.

Vous pouvez afficher la liste des sauvegardes créées pour vos partages de fichiers et disques sur la page *backups*. Les sauvegardes s'affichent en fonction du locataire sélectionné.



== Modifier une stratégie ou un planning de sauvegarde

Lorsque vous créez ou modifiez des partages de fichiers et des disques, vous pouvez définir leurs stratégies de sauvegarde. Les sauvegardes sont effectuées en back-end, en fonction des règles spécifiées par vous. Pour plus d'informations, voir : link:sewebiug_create_a_new_file_share.html["créez un partage de fichiers"] ou link:sewebiug_create_a_new_disk.html["créer un disque"].

.Étapes
. Activer *Stratégie de sauvegarde*.
. Spécifiez la zone de sauvegarde et le nombre de sauvegardes à effectuer sur une base ponctuelle, quotidienne, hebdomadaire et/ou mensuelle.
. Cliquez sur *Créer*.



NOTE: Vous pouvez également planifier des sauvegardes en modifiant la stratégie de sauvegarde d'un partage de fichiers ou d'un disque existant.



== Modifier ou déconnecter la source d'une sauvegarde

Pour un objet de sauvegarde sélectionné d'un partage de fichiers ou d'un disque, vous pouvez désactiver la sauvegarde ou détacher l'objet de sauvegarde de sa source et en faire une sauvegarde orpheline. Cette opération interrompt la relation SnapMirror avec la source. Vous pouvez également modifier le nombre de sauvegardes à effectuer de façon ponctuelle, quotidienne, hebdomadaire et/ou mensuelle.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *BACKUPS*. Vous pouvez afficher la liste des sauvegardes créées pour tous les objets de votre environnement.
. Localisez la sauvegarde dans la liste (en effectuant une recherche par le nom du volume) et cliquez sur l'icône de modification, à la fin de la ligne.
. Modifiez la source de sauvegarde et le nombre de chaque type de sauvegarde, le cas échéant. Pour interrompre la relation SnapMirror avec le volume source, définissez la source de sauvegarde sur *aucun (orphelin)*. Les sauvegardes sont conservées en tant que sauvegardes orphelines pour la restauration, même lorsque les volumes source sont supprimés. L'état de l'objet de sauvegarde est modifié, et l'état du volume source (orphelin ou supprimé) est ajouté au nom du volume source dans la même liste. Pour plus d'informations sur l'état d'un objet, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["ici"]
. Cliquez sur *Done*. Le snapshot est modifié. Si vous avez rompu la relation SnapMirror avec la source, c'est-à-dire, orphelin l'objet de sauvegarde, le nom de la source dans l'onglet *backups* apparaît comme `deted`.



NOTE: Vous pouvez également rompre la relation SnapMirror avec le volume source en désactivant *Backup Policy* pour le volume dans les écrans Créer un partage/Modifier le partage et Créer un disque/Modifier le disque.



== Demandez de l'aide pour la sauvegarde et la restauration

C'est possible link:sewebiug_raise_a_service_request.html["demander un service"] pour restaurer un partage de fichiers ou un disque à partir d'un point de restauration spécifique.

.Étapes
. Sélectionnez *SUPPORT* dans le volet de navigation de gauche et sélectionnez *demandes de service*.
. Cliquez sur *Nouvelle demande de service*.
. Sélectionnez *Backup Restore* comme catégorie pour la demande de service.
. Spécifiez d'autres détails et continuez.




== Supprime un objet de sauvegarde

La suppression d'un volume de sauvegarde inutilisé permet d'augmenter l'espace de stockage. Pour supprimer un volume de sauvegarde et des points de récupération de la source supprimée, vous devez utiliser l'API backups.


NOTE: Lorsqu'une sauvegarde est supprimée, tous les points de restauration de la sauvegarde sont supprimés. De même, même si vous supprimez un partage de fichiers ou un disque primaire, la sauvegarde est conservée comme sauvegarde orpheline, avec tous les points de restauration à restaurer.
