---
sidebar: sidebar 
permalink: sewebiug_define_network_configurations.html 
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port 
summary: Créez et supprimez des sous-réseaux 
---
= Définissez des configurations réseau pour les locataires et sous-locataires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un fournisseur de services ou un administrateur partenaire peut définir des configurations réseau pour les locataires en fonction de leurs zones d'abonnement et attribuer des VLAN à chaque configuration réseau. Ils peuvent également créer un sous-réseau avec chaque VLAN appartenant à la même zone et à la même location, et l'affecter à un sous-locataire sous cette location.

Un réseau de locataires préconfiguré est requis la création du sous-réseau. Un sous-réseau est requis lorsqu'un sous-locataire ou un client final provisionne des serveurs de fichiers ou des magasins de blocs. Les machines virtuelles de stockage de fichiers et de blocs sont la propriété des sous-locataires du moteur de services NetApp, tandis qu'elles sont la propriété des IPspaces dans ONTAP. Lorsque vous définissez la limite réseau au niveau du sous-locataire, le sous-locataire du moteur de services NetApp est mappé à un seul IPspace ONTAP pour cette zone. Cela élimine les risques et garantit que deux sous-locataires distincts ne sélectionnent pas le même ID VLAN et se terminent dans le même IPspace.

* Il peut y avoir plusieurs sous-réseaux créés dans chaque zone. Pour chaque zone sous une location, une liste de VLAN est allouée. Pour tous les VLAN disponibles, les sous-réseaux correspondants peuvent être créés. Il existe un mappage 1:1 entre un sous-réseau et un VLAN. Alors qu'il y a un mappage à plusieurs entre les sous-réseaux et la zone.
* Un locataire peut avoir plusieurs sous-réseaux, un pour chaque VLAN disponible sous une zone. Elles sont affichées sous une configuration réseau unique pour chaque zone.
* Il ne peut y avoir qu'un seul VLAN pour chaque sous-réseau réseau réseau. Chaque configuration réseau affiche la liste des VLAN disponibles.
* Un seul sous-réseau peut être créé pour une combinaison zone et VLAN pour un sous-tenant.



NOTE: Un administrateur de tenant ne peut afficher que les configurations réseau de sa location et des sous-réseaux de ses sous-locataires.



== Définissez une configuration réseau pour un locataire

En tant qu'administrateur partenaire, vous pouvez créer des configurations réseau pour chaque locataire. Un pool VLAN unique et configurable peut être alloué à chaque locataire en fonction de ses besoins. Lorsqu'un locataire est supprimé, les VLAN associés sont rélibérés vers le pool VLAN du locataire.

.Avant de commencer
* Assurez-vous que les locataires ont été créés
* Vous devez connaître la configuration de la zone, des réseaux locaux virtuels, du sous-réseau CIDR et du port override


.Étapes
. Dans *ADMINISTRATION* > *tenants*, sélectionnez le locataire requis.
. Cliquez sur l'icône réseau. L'écran réseaux s'affiche avec la liste des configurations réseau pour le locataire.
. Cliquez sur *Créer réseau*. Spécifiez la zone, le VLAN et le remplacement du port, le cas échéant. Si le remplacement du port est défini, sélectionnez le port affecté dans la liste déroulante. Pour toutes les connexions réseau de ce tenant, ce port est utilisé, et non le port par défaut.
+

NOTE: La neutralisation du port est configurée par l'équipe de support lors de la configuration de la zone. Si aucune substitution de port n'est spécifiée, le réseau utilise le port par défaut et crée un nouveau VLAN pour ce tenant.

. Cliquez sur *Créer*. La nouvelle configuration réseau est indiquée pour le locataire sur l'écran réseaux.


Si la configuration réseau d'une zone est créée, vous pouvez uniquement attribuer de nouveaux VLAN à la configuration réseau. Cliquez sur l'icône *+* et ajoutez les détails de remplacement du VLAN et du port. Cliquez sur *mettre à jour*.



== Créez un sous-réseau pour un sous-locataire

En tant qu'administrateur partenaire, vous pouvez créer des sous-réseaux pour vos sous-locataires à partir de *RÉSEAUX* > *sous-réseaux*. La définition de sous-réseau inclut l'ID VLAN implémenté dans ONTAP, la plage d'adresses CIDR et une spécification de route. Un sous-réseau est aligné sur un VLAN au sein d'un locataire et d'une zone. Vous ne pouvez pas créer deux sous-réseaux avec le même VLAN pour une zone.

.Avant de commencer
* La configuration VLAN et zone doit déjà avoir été complète pour le locataire
* Vous devez connaître les exigences relatives à la création du sous-réseau


.Étapes
. Sélectionnez le locataire requis. Les sous-locataires pour lesquels vous créez les sous-réseaux doivent être sous ce locataire.
. Cliquez sur *RÉSEAUX* > *sous-réseaux*. Vous pouvez afficher la liste des sous-réseaux créés pour vos sous-locataires sur la page *sous-réseaux*.
. Cliquez sur *Créer un sous-réseau*.
. Spécifiez le sous-locataire, la zone, le nom du sous-réseau, le VLAN et le CPCMI du sous-réseau. Vous pouvez également ajouter des spécifications de routage et des balises.
+

NOTE: Dans la spécification de route, la *destination* doit être unique et faire partie du VLAN mentionné, et plusieurs routes peuvent avoir la même valeur pour *métrique*.

. Cliquez sur *Créer*.



NOTE: Vous ne pouvez ni modifier ni supprimer un sous-réseau. Vous pouvez uniquement modifier les balises qui lui sont associées.
