---
sidebar: sidebar 
permalink: sewebiug_create_object_storage_user.html 
keywords: netapp, keystone, create, object, storage, user, 
summary: Keystone crée un utilisateur de stockage objet 
---
= Créer un utilisateur de stockage objet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer des utilisateurs et les ajouter à des groupes spécifiques pour leur attribuer un accès au stockage objet.

Comme un utilisateur de stockage objet appartient à un groupe de stockage objet, le groupe de stockage objet doit exister avant de pouvoir créer l'utilisateur.

.Étapes
. Accédez à *STOCKAGE D'OBJETS > gestion des utilisateurs > utilisateurs*.
. Assurez-vous que le sous-locataire correct est sélectionné et que vous avez cliqué sur l'onglet *utilisateurs*.
. Cliquez sur *Créer un utilisateur*.
. Dans la boîte de dialogue Créer un utilisateur :
+
.. Entrez le nom d'utilisateur.
.. Sélectionnez le groupe auquel appartient le membre.


. Cliquez sur *Créer*. Cela crée un travail pour créer l'utilisateur avec les paramètres spécifiés.


Créer un utilisateur est exécuté comme une tâche asynchrone. Vous pouvez :

* Vérifiez l'état du travail dans la liste des travaux. Pour plus d'informations, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["Tâches et indicateur d'état du travail"].
* Une fois le travail terminé, vérifiez l'état du partage dans la liste des utilisateurs.

