---
sidebar: sidebar 
permalink: sewebiug_modify_user_details.html 
keywords: netapp, keystone, modify, user, details, 
summary: 'Keystone modifie les détails de l"utilisateur' 
---
= Modifier les détails de l'utilisateur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez cette méthode pour modifier les détails d'un utilisateur. Vous pouvez :

* Modifiez le prénom, le nom et le nom d'affichage de l'utilisateur.
* Ajoutez ou supprimez des tenlocations auxquelles l'utilisateur a accès.
* Modifiez le rôle de l'utilisateur dans chaque location à laquelle l'utilisateur a accès.


.Étapes
. Sélectionnez *ADMINISTRATION > utilisateurs*.
. Localisez l'utilisateur dans la liste et cliquez sur l'icône Modifier.
. Dans la boîte de dialogue Modifier l'utilisateur, apportez les modifications nécessaires.
. Pour modifier le rôle de l'utilisateur dans une location, localisez la location dans la liste locations et sélectionnez le nouveau rôle.
. Pour accorder l'accès de l'utilisateur à une autre location, cliquez sur *Ajouter une location* et sélectionnez le locataire et le rôle de l'utilisateur dans cette location dans les champs de la nouvelle entrée.
. Pour supprimer l'accès de l'utilisateur à une location, localisez la location dans la liste locations et sélectionnez l'icône Supprimer.
. Cliquez sur *mettre à jour*.

