---
sidebar: sidebar 
permalink: sewebiug_track_a_service_request.html 
keywords: netapp, keystone, track, service, request, 
summary: 'Keystone : suivre une demande de service' 
---
= Suivre une demande de service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une demande de service suit la procédure décrite dans cette section.

Le tableau suivant fournit une liste des États des demandes de service.

|===
| État | Description 


| Nouveau | Cette demande vient d'être créée. 


| La transparence | La demande est en cours d'examen/de réalisation. 


| En attente | La demande est en attente d'une action d'un tiers (en attente d'informations supplémentaires). 


| Résolu | La demande a été résolue. 


| Mis en attente | La demande attend une activité qui ne maîtrise pas les services de support et peut prendre un certain temps avant que la demande ne puisse être traitée. 


| Fermée | La demande est fermée. 
|===
Vous pouvez suivre l'état d'une demande de service en consultant le statut de NetApp Service Engine décrit ci-dessous. Vous pouvez également suivre le statut des e-mails automatisés envoyés lors de ce processus.

. Dans le menu, sélectionnez *support > demandes de service*. La liste est filtrée en fonction de la priorité par défaut «urgent».
. Sélectionnez la priorité et l'état requis pour afficher la liste des demandes de service.
. Localisez la demande de service dans la liste et affichez son statut dans la colonne `Enregistrer`.

