---
sidebar: sidebar 
permalink: sewebiug_delete_an_s3_key_for_a_user.html 
keywords: netapp, keystone, s3, key, user, 
summary: 'Keystone supprime une clé S3 d"un utilisateur' 
---
= Supprimez une clé S3 d'un utilisateur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez cette méthode pour supprimer une clé S3 pour un utilisateur.

.Étapes
. Afficher l'utilisateur de stockage objet link:sewebiug_view_the_object_storage_group_and_users.html["Afficher les utilisateurs et les groupes de stockage objet"].
. Assurez-vous que le sous-locataire correct est sélectionné et que vous avez cliqué sur l'onglet *utilisateurs*.
. Localisez l'utilisateur dans la liste et cliquez sur l'icône clé de ce groupe.
+
Pour plus d'informations sur l'utilisation des éléments dans les listes, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Actions de vue de liste"].

. La boîte de dialogue *Manage S3 Keys* s'affiche et affiche la liste des touches de l'utilisateur.
. Dans la liste des touches, localisez la touche à supprimer et cliquez sur l'icône *Supprimer*.
. Cliquez sur *confirmer* pour confirmer l'action de suppression. La clé est supprimée de la liste des clés utilisateur.
. Cliquez sur *Fermer* pour fermer la boîte de dialogue gestion des clés S3.

