---
sidebar: sidebar 
permalink: sewebiug_managing_azure_volumes.html 
keywords: netapp, keystone, managing, azure, volumes, 
summary: Gestion des volumes Azure par Keystone 
---
= Gestion des volumes Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section décrit comment gérer des volumes Azure.


NOTE: La gestion des volumes Azure requiert un accès administrateur client.

Cette section décrit comment effectuer les tâches suivantes :

* Afficher la liste des volumes Azure.
* Ajouter un volume Azure
* Modifier les détails des volumes Azure
* Supprimez un volume Azure.




=== Afficher la liste des volumes Azure

La liste volumes Azure affiche la liste des pools de volumes Azure pour un sous-locataire et un emplacement spécifiés. Pour afficher la liste, sélectionnez *SERVICES DE FICHIERS > Azure volumes* dans le menu.

La liste affiche des informations simples sur chaque volume Azure. Les icônes d'action en regard de chaque volume Azure vous permettent de modifier ou de supprimer le volume Azure.



=== Ajouter un volume Azure

Cette section décrit l'ajout d'un volume Azure.

Vous aurez besoin des éléments suivants :

* Sous-locataire auquel appartient le volume Azure
* Le compte ANF
* Réseau virtuel Azure (vnet) et sous-réseau
* Le pool de capacité pour héberger le volume
* Nom du volume
* Le chemin du fichier
* Le quota (taille) du volume


.Étapes
. Sélectionnez *SERVICES DE FICHIERS > Azure volumes* dans le menu.
. Cliquez sur *Créer*.
. Dans la boîte de dialogue Créer un volume Azure, spécifiez le sous-locataire, le compte ANF, le vnet, le sous-réseau, le pool de capacité, le nom du volume, le chemin de fichier et le quota. Assurez-vous que vous entrez un chemin de fichier unique pour une création réussie du volume.
. Si nécessaire, ajoutez des balises au volume.
. Cliquez sur *Créer*. Lorsqu'un volume Azure est créé, l'état du volume devient `séparé` (peut être affiché dans la liste des volumes Azure).




=== Modifier les détails des volumes Azure

Utilisez cette méthode pour modifier les détails d'un volume Azure. Vous pouvez modifier le chemin d'accès et le quota de fichiers, et ajouter ou supprimer des balises.

.Étapes
. Sélectionnez *SERVICES DE FICHIERS > Azure volumes* dans le menu.
. Dans la liste, recherchez le volume Azure et cliquez sur l'icône de modification.
. Dans la boîte de dialogue gérer le volume Azure, apportez les modifications requises. Si vous modifiez le chemin de fichier ou le quota, assurez-vous que le chemin de fichier est unique et que le quota ne dépasse pas le quota disponible dans le pool.
. Cliquez sur *mettre à jour*.




=== Supprimez un volume Azure

Utilisez cette méthode pour supprimer un volume Azure.

.Étapes
. Sélectionnez *SERVICES DE FICHIERS > Azure volumes* dans le menu.
. Recherchez le volume Azure dans la liste et cliquez sur l'icône de suppression.
. Dans la boîte de dialogue confirmer la suppression, entrez le nom du volume Azure à supprimer.
. Cliquez sur *confirmer*.

