---
sidebar: sidebar 
permalink: sewebiug_create_an_adhoc_snapshot_of_a_disk.html 
keywords: netapp, keystone, create, adhoc, snapshot, disk 
summary: 'Keystone crée un snapshot ad hoc d"un disque' 
---
= Créer un snapshot ad hoc d'un disque
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette section décrit comment créer un instantané ad hoc d'un disque.

.Étapes
. Afficher le link:sewebiug_view_disks.html#view-disks["Liste des disques"].
. Localisez le disque dans la liste et cliquez sur l'icône d'instantané correspondant à ce disque. (Pour plus de détails sur l'utilisation des éléments dans les listes, voir link:sewebiug_netapp_service_engine_web_interface_overview#list-view["Actions de vue de liste"]).
. Dans la boîte de dialogue Créer un instantané, entrez un nom pour votre instantané et cliquez sur *Créer*.


.Une fois que vous avez terminé
Cette copie peut prendre quelques minutes. Si disponible, vous pouvez créer un autre disque en clonant ce snapshot. Pour plus d'informations, reportez-vous à la section link:sewebiug_create_a_disk_from_a_snapshot.html["Créer un disque à partir d'un snapshot"].
