---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_user.html 
keywords: netapp, keystone, modify, object, storage, user, 
summary: Keystone modifie un utilisateur de stockage objet 
---
= Modifier un utilisateur de stockage objet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez cette méthode pour modifier les détails d'un utilisateur de stockage objet, par exemple le nom d'utilisateur et le groupe auquel il est affecté.

.Étapes
. Afficher l'utilisateur de stockage objet link:sewebiug_view_the_object_storage_group_and_users.html["Afficher les utilisateurs et les groupes de stockage objet"].
. Assurez-vous que le sous-locataire correct est sélectionné et que vous avez cliqué sur l'onglet *utilisateurs*.
. Localisez l'utilisateur dans la liste et cliquez sur l'icône de modification de cet utilisateur.
+
Pour plus d'informations sur l'utilisation des éléments dans les listes, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Actions de vue de liste"].

. Dans la boîte de dialogue *Modifier l'utilisateur*, modifiez le groupe de stockage d'objets pour l'utilisateur.
. Cliquez sur *mettre à jour*. Cela crée un travail pour mettre à jour le groupe pour l'utilisateur. Pour plus d'informations sur le suivi des travaux, reportez-vous à la section link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["ici"].

