---
sidebar: sidebar 
permalink: sewebiug_managing_service_requests_overview.html 
keywords: netapp, keystone, managing, service, requests, overview, 
summary: Présentation de la gestion des demandes de service par Keystone 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les demandes de service vous permettent de soulever un problème avec l'équipe GSSC pour qu'elle puisse résoudre le problème et mettre à jour l'état que vous souhaitez afficher.


NOTE: Vous pouvez afficher le menu *support > demandes de service* uniquement si vous êtes un administrateur partenaire. En tant qu'administrateur partenaire, vous pouvez également afficher la liste des demandes de service émises pour le locataire sélectionné dans le tableau de bord. Vous ne pouvez pas soumettre de demande de service au support NetApp si vous êtes un administrateur de locataires.

Le workflow est à link:https://docs.netapp.com/us-en/keystone/sewebiug_service_request_process.html["Processus de demande de service"]

Faire une demande de service pour :

* La restauration des sauvegardes
* Basculement de reprise d'activité
* Problème technique avec le moteur de service NetApp
* Volumes non standard : les volumes importés dans votre abonnement Flex partagent la même norme que les disques et partages de fichiers existants sur le moteur de services NetApp. Après importation, ces disques et partages de fichiers sont classés avec le statut «non standard». Vous pouvez soumettre une demande de service pour changer leur statut à un état standard.
* Tout autre problème qui n'est pas couvert dans cette liste.


Les autres sujets abordés dans cette section abordent :

* Comment demander un service
* Comment suivre une demande de service
* Le processus de demande de service

